//
//  EmojiDataModel.swift
//  Qoop
//
//  Created by Vlad on 13/7/25.
//

import Foundation
import SwiftUI

struct Emoji: Identifiable {
    let id = UUID()
    let symbol: String
    let name: String
}

struct EmojiCategory {
    let name: String
    let emojis: [Emoji]
}

let emojiCategories: [EmojiCategory] = [
    EmojiCategory(name: "Smileys & Emotion",emojis: [
        Emoji(symbol: "😀", name: "Grinning Face"),
        Emoji(symbol: "😃", name: "Grinning Face With Big Eyes"),
        Emoji(symbol: "😄", name: "Grinning Face With Smiling Eyes"),
        Emoji(symbol: "😁", name: "Beaming Face With Smiling Eyes"),
        Emoji(symbol: "😆", name: "Grinning Squinting Face"),
        Emoji(symbol: "😅", name: "Grinning Face With Sweat"),
        Emoji(symbol: "😂", name: "Face With Tears of Joy"),
        Emoji(symbol: "🤣", name: "Rolling on the Floor Laughing"),
        Emoji(symbol: "😊", name: "Smiling Face With Smiling Eyes"),
        Emoji(symbol: "😇", name: "Smiling Face With Halo"),
        Emoji(symbol: "🙂", name: "Slightly Smiling Face"),
        Emoji(symbol: "🙃", name: "Upside-Down Face"),
        Emoji(symbol: "😉", name: "Winking Face"),
        Emoji(symbol: "😌", name: "Relieved Face"),
        Emoji(symbol: "😍", name: "Smiling Face With Heart-Eyes"),
        Emoji(symbol: "🥰", name: "Smiling Face With Hearts"),
        Emoji(symbol: "😘", name: "Face Blowing a Kiss"),
        Emoji(symbol: "😗", name: "Kissing Face"),
        Emoji(symbol: "😙", name: "Kissing Face With Smiling Eyes"),
        Emoji(symbol: "😚", name: "Kissing Face With Closed Eyes"),
        Emoji(symbol: "😋", name: "Face Savoring Food"),
        Emoji(symbol: "😛", name: "Face With Tongue"),
        Emoji(symbol: "😝", name: "Squinting Face With Tongue"),
        Emoji(symbol: "😜", name: "Winking Face With Tongue"),
        Emoji(symbol: "🤪", name: "Zany Face"),
        Emoji(symbol: "🤨", name: "Face With Raised Eyebrow"),
        Emoji(symbol: "🧐", name: "Face With Monocle"),
        Emoji(symbol: "🤓", name: "Nerd Face"),
        Emoji(symbol: "😎", name: "Smiling Face With Sunglasses"),
        Emoji(symbol: "🥸", name: "Disguised Face"),
        Emoji(symbol: "🤩", name: "Star-Struck"),
        Emoji(symbol: "🥳", name: "Partying Face"),
        Emoji(symbol: "😏", name: "Smirking Face"),
        Emoji(symbol: "😒", name: "Unamused Face"),
        Emoji(symbol: "😞", name: "Disappointed Face"),
        Emoji(symbol: "😔", name: "Pensive Face"),
        Emoji(symbol: "😟", name: "Worried Face"),
        Emoji(symbol: "😕", name: "Confused Face"),
        Emoji(symbol: "🙁", name: "Slightly Frowning Face"),
        Emoji(symbol: "☹️", name: "Frowning Face"),
        Emoji(symbol: "😣", name: "Persevering Face"),
        Emoji(symbol: "😖", name: "Confounded Face"),
        Emoji(symbol: "😫", name: "Tired Face"),
        Emoji(symbol: "😩", name: "Weary Face"),
        Emoji(symbol: "🥺", name: "Pleading Face"),
        Emoji(symbol: "😢", name: "Crying Face"),
        Emoji(symbol: "😭", name: "Loudly Crying Face"),
        Emoji(symbol: "😤", name: "Face With Steam From Nose"),
        Emoji(symbol: "😠", name: "Angry Face"),
        Emoji(symbol: "😡", name: "Pouting Face"),
        Emoji(symbol: "🤬", name: "Face With Symbols on Mouth"),
        Emoji(symbol: "🤯", name: "Exploding Head"),
        Emoji(symbol: "😳", name: "Flushed Face"),
        Emoji(symbol: "🥵", name: "Hot Face"),
        Emoji(symbol: "🥶", name: "Cold Face"),
        Emoji(symbol: "😱", name: "Face Screaming in Fear"),
        Emoji(symbol: "😨", name: "Fearful Face"),
        Emoji(symbol: "😰", name: "Anxious Face With Sweat"),
        Emoji(symbol: "😥", name: "Sad but Relieved Face"),
        Emoji(symbol: "😓", name: "Downcast Face With Sweat"),
        Emoji(symbol: "🫣", name: "Face With Peeking Eye"),
        Emoji(symbol: "🤗", name: "Hugging Face"),
        Emoji(symbol: "🫢", name: "Face With Open Eyes and Hand Over Mouth"),
        Emoji(symbol: "🫡", name: "Saluting Face"),
        Emoji(symbol: "🤔", name: "Thinking Face"),
        Emoji(symbol: "🤭", name: "Face With Hand Over Mouth"),
        Emoji(symbol: "🤫", name: "Shushing Face"),
        Emoji(symbol: "🤥", name: "Lying Face"),
        Emoji(symbol: "😶", name: "Face Without Mouth"),
        Emoji(symbol: "😐", name: "Neutral Face"),
        Emoji(symbol: "😑", name: "Expressionless Face"),
        Emoji(symbol: "😬", name: "Grimacing Face"),
        Emoji(symbol: "🫨", name: "Shaking Face"),
        Emoji(symbol: "🫠", name: "Melting Face"),
        Emoji(symbol: "🙄", name: "Face With Rolling Eyes"),
        Emoji(symbol: "😯", name: "Hushed Face"),
        Emoji(symbol: "😦", name: "Frowning Face With Open Mouth"),
        Emoji(symbol: "😧", name: "Anguished Face"),
        Emoji(symbol: "😮", name: "Face With Open Mouth"),
        Emoji(symbol: "😲", name: "Astonished Face"),
        Emoji(symbol: "🥱", name: "Yawning Face"),
        Emoji(symbol: "😴", name: "Sleeping Face"),
        Emoji(symbol: "🤤", name: "Drooling Face"),
        Emoji(symbol: "😪", name: "Sleepy Face"),
        Emoji(symbol: "😵", name: "Dizzy Face"),
        Emoji(symbol: "😵‍💫", name: "Face With Spiral Eyes"),
        Emoji(symbol: "🫥", name: "Dotted Line Face"),
        Emoji(symbol: "🤐", name: "Zipper-Mouth Face"),
        Emoji(symbol: "🥴", name: "Woozy Face"),
        Emoji(symbol: "🤢", name: "Nauseated Face"),
        Emoji(symbol: "🤮", name: "Face Vomiting"),
        Emoji(symbol: "🤧", name: "Sneezing Face"),
        Emoji(symbol: "😷", name: "Face With Medical Mask"),
        Emoji(symbol: "🤒", name: "Face With Thermometer"),
        Emoji(symbol: "🤕", name: "Face With Head-Bandage"),
        Emoji(symbol: "🤑", name: "Money-Mouth Face"),
        Emoji(symbol: "🤠", name: "Cowboy Hat Face"),
        Emoji(symbol: "😈", name: "Smiling Face With Horns"),
        Emoji(symbol: "👿", name: "Angry Face With Horns"),
        Emoji(symbol: "👹", name: "Ogre"),
        Emoji(symbol: "👺", name: "Goblin"),
        Emoji(symbol: "🤡", name: "Clown Face"),
        Emoji(symbol: "💩", name: "Pile of Poo"),
        Emoji(symbol: "👻", name: "Ghost"),
        Emoji(symbol: "💀", name: "Skull"),
        Emoji(symbol: "☠️", name: "Skull and Crossbones"),
        Emoji(symbol: "👽", name: "Alien"),
        Emoji(symbol: "👾", name: "Alien Monster"),
        Emoji(symbol: "🤖", name: "Robot"),
        Emoji(symbol: "🎃", name: "Jack-O-Lantern"),
        Emoji(symbol: "😺", name: "Grinning Cat"),
        Emoji(symbol: "😸", name: "Grinning Cat With Smiling Eyes"),
        Emoji(symbol: "😹", name: "Cat With Tears of Joy"),
        Emoji(symbol: "😻", name: "Smiling Cat With Heart-Eyes"),
        Emoji(symbol: "😼", name: "Cat With Wry Smile"),
        Emoji(symbol: "😽", name: "Kissing Cat"),
        Emoji(symbol: "🙀", name: "Weary Cat"),
        Emoji(symbol: "😿", name: "Crying Cat"),
        Emoji(symbol: "😾", name: "Pouting Cat"),
        Emoji(symbol: "❤️", name: "Red Heart"),
        Emoji(symbol: "🧡", name: "Orange Heart"),
        Emoji(symbol: "💛", name: "Yellow Heart"),
        Emoji(symbol: "💚", name: "Green Heart"),
        Emoji(symbol: "💙", name: "Blue Heart"),
        Emoji(symbol: "💜", name: "Purple Heart"),
        Emoji(symbol: "🖤", name: "Black Heart"),
        Emoji(symbol: "🤍", name: "White Heart"),
        Emoji(symbol: "🤎", name: "Brown Heart"),
        Emoji(symbol: "💔", name: "Broken Heart"),
        Emoji(symbol: "❣️", name: "Heart Exclamation"),
        Emoji(symbol: "💕", name: "Two Hearts"),
        Emoji(symbol: "💞", name: "Revolving Hearts"),
        Emoji(symbol: "💓", name: "Beating Heart"),
        Emoji(symbol: "💗", name: "Growing Heart"),
        Emoji(symbol: "💖", name: "Sparkling Heart"),
        Emoji(symbol: "💘", name: "Heart With Arrow"),
        Emoji(symbol: "💝", name: "Heart With Ribbon"),
        Emoji(symbol: "💟", name: "Heart Decoration"),
        Emoji(symbol: "🩷", name: "Pink Heart"),
        Emoji(symbol: "🩵", name: "Light Blue Heart"),
        Emoji(symbol: "🩶", name: "Grey Heart"),
        Emoji(symbol: "🫶", name: "Heart Hands"),
        Emoji(symbol: "❤️‍🔥", name: "Heart on Fire"),
        Emoji(symbol: "❤️‍🩹", name: "Mending Heart"),
        Emoji(symbol: "😮‍💨", name: "Face Exhaling"),
        Emoji(symbol: "😶‍🌫️", name: "Face in Clouds"),
        Emoji(symbol: "💌", name: "Love Letter"),
        Emoji(symbol: "💋", name: "Kiss Mark"),
        Emoji(symbol: "💯", name: "Hundred Points Symbol"),
        Emoji(symbol: "💢", name: "Anger Symbol"),
        Emoji(symbol: "💥", name: "Collision"),
        Emoji(symbol: "💫", name: "Dizzy"),
        Emoji(symbol: "💦", name: "Sweat Droplets"),
        Emoji(symbol: "💨", name: "Dashing Away"),
        Emoji(symbol: "🕳️", name: "Hole"),
        Emoji(symbol: "💬", name: "Speech Balloon"),
        Emoji(symbol: "👁️‍🗨️", name: "Eye in Speech Bubble"),
        Emoji(symbol: "🗨️", name: "Left Speech Bubble"),
        Emoji(symbol: "🗯️", name: "Right Anger Bubble"),
        Emoji(symbol: "💭", name: "Thought Balloon"),
        Emoji(symbol: "💤", name: "Zzz")
    ]),
    EmojiCategory(name: "People & Body",emojis: [
        // Hand gestures
        Emoji(symbol: "👋", name: "Waving Hand"),
        Emoji(symbol: "🤚", name: "Raised Back of Hand"),
        Emoji(symbol: "🖐️", name: "Hand With Fingers Splayed"),
        Emoji(symbol: "✋", name: "Raised Hand"),
        Emoji(symbol: "🖖", name: "Vulcan Salute"),
        Emoji(symbol: "🫱", name: "Rightwards Hand"),
        Emoji(symbol: "🫲", name: "Leftwards Hand"),
        Emoji(symbol: "🫳", name: "Palm Down Hand"),
        Emoji(symbol: "🫴", name: "Palm Up Hand"),
        Emoji(symbol: "👌", name: "OK Hand"),
        Emoji(symbol: "🤌", name: "Pinched Fingers"),
        Emoji(symbol: "🤏", name: "Pinching Hand"),
        Emoji(symbol: "✌️", name: "Victory Hand"),
        Emoji(symbol: "🤞", name: "Crossed Fingers"),
        Emoji(symbol: "🫰", name: "Hand With Index Finger and Thumb Crossed"),
        Emoji(symbol: "🤟", name: "Love-You Gesture"),
        Emoji(symbol: "🤘", name: "Sign of the Horns"),
        Emoji(symbol: "🤙", name: "Call Me Hand"),
        Emoji(symbol: "👈", name: "Backhand Index Pointing Left"),
        Emoji(symbol: "👉", name: "Backhand Index Pointing Right"),
        Emoji(symbol: "👆", name: "Backhand Index Pointing Up"),
        Emoji(symbol: "🖕", name: "Middle Finger"),
        Emoji(symbol: "👇", name: "Backhand Index Pointing Down"),
        Emoji(symbol: "☝️", name: "Index Pointing Up"),
        Emoji(symbol: "🫵", name: "Index Pointing at the Viewer"),
        Emoji(symbol: "👍", name: "Thumbs Up"),
        Emoji(symbol: "👎", name: "Thumbs Down"),
        Emoji(symbol: "✊", name: "Raised Fist"),
        Emoji(symbol: "👊", name: "Oncoming Fist"),
        Emoji(symbol: "🤛", name: "Left-Facing Fist"),
        Emoji(symbol: "🤜", name: "Right-Facing Fist"),
        Emoji(symbol: "👏", name: "Clapping Hands"),
        Emoji(symbol: "🙌", name: "Raising Hands"),
        Emoji(symbol: "🫶", name: "Heart Hands"),
        Emoji(symbol: "👐", name: "Open Hands"),
        Emoji(symbol: "🤲", name: "Palms Up Together"),
        Emoji(symbol: "🤝", name: "Handshake"),
        Emoji(symbol: "🙏", name: "Folded Hands"),
        // Other body parts
        Emoji(symbol: "✍️", name: "Writing Hand"),
        Emoji(symbol: "💅", name: "Nail Polish"),
        Emoji(symbol: "🤳", name: "Selfie"),
        Emoji(symbol: "💪", name: "Flexed Biceps"),
        Emoji(symbol: "🦾", name: "Mechanical Arm"),
        Emoji(symbol: "🦿", name: "Mechanical Leg"),
        Emoji(symbol: "🦵", name: "Leg"),
        Emoji(symbol: "🦶", name: "Foot"),
        Emoji(symbol: "👂", name: "Ear"),
        Emoji(symbol: "🦻", name: "Ear With Hearing Aid"),
        Emoji(symbol: "👃", name: "Nose"),
        Emoji(symbol: "🧠", name: "Brain"),
        Emoji(symbol: "🫀", name: "Anatomical Heart"),
        Emoji(symbol: "🫁", name: "Lungs"),
        Emoji(symbol: "🦷", name: "Tooth"),
        Emoji(symbol: "🦴", name: "Bone"),
        Emoji(symbol: "👀", name: "Eyes"),
        Emoji(symbol: "👁️", name: "Eye"),
        Emoji(symbol: "👅", name: "Tongue"),
        Emoji(symbol: "👄", name: "Mouth"),
        Emoji(symbol: "🫦", name: "Biting Lip"),
        // People
        Emoji(symbol: "👶", name: "Baby"),
        Emoji(symbol: "🧒", name: "Child"),
        Emoji(symbol: "👦", name: "Boy"),
        Emoji(symbol: "👧", name: "Girl"),
        Emoji(symbol: "🧑", name: "Person"),
        Emoji(symbol: "👱", name: "Person: Blond Hair"),
        Emoji(symbol: "👨", name: "Man"),
        Emoji(symbol: "🧔", name: "Person: Beard"),
        Emoji(symbol: "🧔‍♂️", name: "Man: Beard"),
        Emoji(symbol: "🧔‍♀️", name: "Woman: Beard"),
        Emoji(symbol: "👨‍🦰", name: "Man: Red Hair"),
        Emoji(symbol: "👨‍🦱", name: "Man: Curly Hair"),
        Emoji(symbol: "👨‍🦳", name: "Man: White Hair"),
        Emoji(symbol: "👨‍🦲", name: "Man: Bald"),
        Emoji(symbol: "👩", name: "Woman"),
        Emoji(symbol: "👩‍🦰", name: "Woman: Red Hair"),
        Emoji(symbol: "🧑‍🦰", name: "Person: Red Hair"),
        Emoji(symbol: "👩‍🦱", name: "Woman: Curly Hair"),
        Emoji(symbol: "🧑‍🦱", name: "Person: Curly Hair"),
        Emoji(symbol: "👩‍🦳", name: "Woman: White Hair"),
        Emoji(symbol: "🧑‍🦳", name: "Person: White Hair"),
        Emoji(symbol: "👩‍🦲", name: "Woman: Bald"),
        Emoji(symbol: "🧑‍🦲", name: "Person: Bald"),
        Emoji(symbol: "👱‍♀️", name: "Woman: Blond Hair"),
        Emoji(symbol: "👱‍♂️", name: "Man: Blond Hair"),
        Emoji(symbol: "🧓", name: "Older Person"),
        Emoji(symbol: "👴", name: "Old Man"),
        Emoji(symbol: "👵", name: "Old Woman"),
        // Person gestures
        Emoji(symbol: "🙍", name: "Person Frowning"),
        Emoji(symbol: "🙍‍♂️", name: "Man Frowning"),
        Emoji(symbol: "🙍‍♀️", name: "Woman Frowning"),
        Emoji(symbol: "🙎", name: "Person Pouting"),
        Emoji(symbol: "🙎‍♂️", name: "Man Pouting"),
        Emoji(symbol: "🙎‍♀️", name: "Woman Pouting"),
        Emoji(symbol: "🙅", name: "Person Gesturing No"),
        Emoji(symbol: "🙅‍♂️", name: "Man Gesturing No"),
        Emoji(symbol: "🙅‍♀️", name: "Woman Gesturing No"),
        Emoji(symbol: "🙆", name: "Person Gesturing OK"),
        Emoji(symbol: "🙆‍♂️", name: "Man Gesturing OK"),
        Emoji(symbol: "🙆‍♀️", name: "Woman Gesturing OK"),
        Emoji(symbol: "💁", name: "Person Tipping Hand"),
        Emoji(symbol: "💁‍♂️", name: "Man Tipping Hand"),
        Emoji(symbol: "💁‍♀️", name: "Woman Tipping Hand"),
        Emoji(symbol: "🙋", name: "Person Raising Hand"),
        Emoji(symbol: "🙋‍♂️", name: "Man Raising Hand"),
        Emoji(symbol: "🙋‍♀️", name: "Woman Raising Hand"),
        Emoji(symbol: "🧏", name: "Deaf Person"),
        Emoji(symbol: "🧏‍♂️", name: "Deaf Man"),
        Emoji(symbol: "🧏‍♀️", name: "Deaf Woman"),
        Emoji(symbol: "🙇", name: "Person Bowing"),
        Emoji(symbol: "🙇‍♂️", name: "Man Bowing"),
        Emoji(symbol: "🙇‍♀️", name: "Woman Bowing"),
        Emoji(symbol: "🤦", name: "Person Facepalming"),
        Emoji(symbol: "🤦‍♂️", name: "Man Facepalming"),
        Emoji(symbol: "🤦‍♀️", name: "Woman Facepalming"),
        Emoji(symbol: "🤷", name: "Person Shrugging"),
        Emoji(symbol: "🤷‍♂️", name: "Man Shrugging"),
        Emoji(symbol: "🤷‍♀️", name: "Woman Shrugging"),
        // Person roles
        Emoji(symbol: "🧑‍⚕️", name: "Health Worker"),
        Emoji(symbol: "👨‍⚕️", name: "Man Health Worker"),
        Emoji(symbol: "👩‍⚕️", name: "Woman Health Worker"),
        Emoji(symbol: "🧑‍🎓", name: "Student"),
        Emoji(symbol: "👨‍🎓", name: "Man Student"),
        Emoji(symbol: "👩‍🎓", name: "Woman Student"),
        Emoji(symbol: "🧑‍🏫", name: "Teacher"),
        Emoji(symbol: "👨‍🏫", name: "Man Teacher"),
        Emoji(symbol: "👩‍🏫", name: "Woman Teacher"),
        Emoji(symbol: "🧑‍⚖️", name: "Judge"),
        Emoji(symbol: "👨‍⚖️", name: "Man Judge"),
        Emoji(symbol: "👩‍⚖️", name: "Woman Judge"),
        Emoji(symbol: "🧑‍🌾", name: "Farmer"),
        Emoji(symbol: "👨‍🌾", name: "Man Farmer"),
        Emoji(symbol: "👩‍🌾", name: "Woman Farmer"),
        Emoji(symbol: "🧑‍🍳", name: "Cook"),
        Emoji(symbol: "👨‍🍳", name: "Man Cook"),
        Emoji(symbol: "👩‍🍳", name: "Woman Cook"),
        Emoji(symbol: "🧑‍⚕️", name: "Doctor"),
        Emoji(symbol: "👨‍⚕️", name: "Male Doctor"),
        Emoji(symbol: "👩‍⚕️", name: "Female Doctor"),
        Emoji(symbol: "🧑‍🔧", name: "Mechanic"),
        Emoji(symbol: "👨‍🔧", name: "Man Mechanic"),
        Emoji(symbol: "👩‍🔧", name: "Woman Mechanic"),
        Emoji(symbol: "🧑‍🏭", name: "Factory Worker"),
        Emoji(symbol: "👨‍🏭", name: "Man Factory Worker"),
        Emoji(symbol: "👩‍🏭", name: "Woman Factory Worker"),
        Emoji(symbol: "🧑‍💼", name: "Office Worker"),
        Emoji(symbol: "👨‍💼", name: "Man Office Worker"),
        Emoji(symbol: "👩‍💼", name: "Woman Office Worker"),
        Emoji(symbol: "🧑‍🔬", name: "Scientist"),
        Emoji(symbol: "👨‍🔬", name: "Man Scientist"),
        Emoji(symbol: "👩‍🔬", name: "Woman Scientist"),
        Emoji(symbol: "🧑‍💻", name: "Technologist"),
        Emoji(symbol: "👨‍💻", name: "Man Technologist"),
        Emoji(symbol: "👩‍💻", name: "Woman Technologist"),
        Emoji(symbol: "🧑‍🎤", name: "Singer"),
        Emoji(symbol: "👨‍🎤", name: "Man Singer"),
        Emoji(symbol: "👩‍🎤", name: "Woman Singer"),
        Emoji(symbol: "🧑‍🎨", name: "Artist"),
        Emoji(symbol: "👨‍🎨", name: "Man Artist"),
        Emoji(symbol: "👩‍🎨", name: "Woman Artist"),
        Emoji(symbol: "🧑‍✈️", name: "Pilot"),
        Emoji(symbol: "👨‍✈️", name: "Man Pilot"),
        Emoji(symbol: "👩‍✈️", name: "Woman Pilot"),
        Emoji(symbol: "🧑‍🚀", name: "Astronaut"),
        Emoji(symbol: "👨‍🚀", name: "Man Astronaut"),
        Emoji(symbol: "👩‍🚀", name: "Woman Astronaut"),
        Emoji(symbol: "🧑‍🚒", name: "Firefighter"),
        Emoji(symbol: "👨‍🚒", name: "Man Firefighter"),
        Emoji(symbol: "👩‍🚒", name: "Woman Firefighter"),
        Emoji(symbol: "👮", name: "Police Officer"),
        Emoji(symbol: "👮‍♂️", name: "Man Police Officer"),
        Emoji(symbol: "👮‍♀️", name: "Woman Police Officer"),
        Emoji(symbol: "🕵️", name: "Detective"),
        Emoji(symbol: "🕵️‍♂️", name: "Man Detective"),
        Emoji(symbol: "🕵️‍♀️", name: "Woman Detective"),
        Emoji(symbol: "💂", name: "Guard"),
        Emoji(symbol: "💂‍♂️", name: "Man Guard"),
        Emoji(symbol: "💂‍♀️", name: "Woman Guard"),
        Emoji(symbol: "🥷", name: "Ninja"),
        Emoji(symbol: "👷", name: "Construction Worker"),
        Emoji(symbol: "👷‍♂️", name: "Man Construction Worker"),
        Emoji(symbol: "👷‍♀️", name: "Woman Construction Worker"),
        // Special people
        Emoji(symbol: "🫅", name: "Person With Crown"),
        Emoji(symbol: "🤴", name: "Prince"),
        Emoji(symbol: "👸", name: "Princess"),
        Emoji(symbol: "👳", name: "Person Wearing Turban"),
        Emoji(symbol: "👳‍♂️", name: "Man Wearing Turban"),
        Emoji(symbol: "👳‍♀️", name: "Woman Wearing Turban"),
        Emoji(symbol: "👲", name: "Person With Skullcap"),
        Emoji(symbol: "🧕", name: "Woman With Headscarf"),
        Emoji(symbol: "🤵", name: "Person in Tuxedo"),
        Emoji(symbol: "🤵‍♂️", name: "Man in Tuxedo"),
        Emoji(symbol: "🤵‍♀️", name: "Woman in Tuxedo"),
        Emoji(symbol: "👰", name: "Person With Veil"),
        Emoji(symbol: "👰‍♂️", name: "Man With Veil"),
        Emoji(symbol: "👰‍♀️", name: "Woman With Veil"),
        Emoji(symbol: "🤱", name: "Breast-Feeding"),
        Emoji(symbol: "🤰", name: "Pregnant Woman"),
        Emoji(symbol: "🫃", name: "Pregnant Man"),
        Emoji(symbol: "🫄", name: "Pregnant Person"),
        Emoji(symbol: "👼", name: "Baby Angel"),
        Emoji(symbol: "🎅", name: "Santa Claus"),
        Emoji(symbol: "🤶", name: "Mrs. Claus"),
        Emoji(symbol: "🧑‍🎄", name: "Mx Claus"),
        // Fantasy
        Emoji(symbol: "🦸", name: "Superhero"),
        Emoji(symbol: "🦸‍♂️", name: "Man Superhero"),
        Emoji(symbol: "🦸‍♀️", name: "Woman Superhero"),
        Emoji(symbol: "🦹", name: "Supervillain"),
        Emoji(symbol: "🦹‍♂️", name: "Man Supervillain"),
        Emoji(symbol: "🦹‍♀️", name: "Woman Supervillain"),
        Emoji(symbol: "🧙", name: "Mage"),
        Emoji(symbol: "🧙‍♂️", name: "Man Mage"),
        Emoji(symbol: "🧙‍♀️", name: "Woman Mage"),
        Emoji(symbol: "🧚", name: "Fairy"),
        Emoji(symbol: "🧚‍♂️", name: "Man Fairy"),
        Emoji(symbol: "🧚‍♀️", name: "Woman Fairy"),
        Emoji(symbol: "🧛", name: "Vampire"),
        Emoji(symbol: "🧛‍♂️", name: "Man Vampire"),
        Emoji(symbol: "🧛‍♀️", name: "Woman Vampire"),
        Emoji(symbol: "🧜", name: "Merperson"),
        Emoji(symbol: "🧜‍♂️", name: "Merman"),
        Emoji(symbol: "🧜‍♀️", name: "Mermaid"),
        Emoji(symbol: "🧝", name: "Elf"),
        Emoji(symbol: "🧝‍♂️", name: "Man Elf"),
        Emoji(symbol: "🧝‍♀️", name: "Woman Elf"),
        Emoji(symbol: "🧞", name: "Genie"),
        Emoji(symbol: "🧞‍♂️", name: "Man Genie"),
        Emoji(symbol: "🧞‍♀️", name: "Woman Genie"),
        Emoji(symbol: "🧟", name: "Zombie"),
        Emoji(symbol: "🧟‍♂️", name: "Man Zombie"),
        Emoji(symbol: "🧟‍♀️", name: "Woman Zombie"),
        Emoji(symbol: "🧌", name: "Troll"),
        // Person activities
        Emoji(symbol: "💆", name: "Person Getting Massage"),
        Emoji(symbol: "💆‍♂️", name: "Man Getting Massage"),
        Emoji(symbol: "💆‍♀️", name: "Woman Getting Massage"),
        Emoji(symbol: "💇", name: "Person Getting Haircut"),
        Emoji(symbol: "💇‍♂️", name: "Man Getting Haircut"),
        Emoji(symbol: "💇‍♀️", name: "Woman Getting Haircut"),
        Emoji(symbol: "🚶", name: "Person Walking"),
        Emoji(symbol: "🚶‍♂️", name: "Man Walking"),
        Emoji(symbol: "🚶‍♀️", name: "Woman Walking"),
        Emoji(symbol: "🚶‍➡️", name: "Person Walking Facing Right"),
        Emoji(symbol: "🚶‍♂️‍➡️", name: "Man Walking Facing Right"),
        Emoji(symbol: "🚶‍♀️‍➡️", name: "Woman Walking Facing Right"),
        Emoji(symbol: "🧍", name: "Person Standing"),
        Emoji(symbol: "🧍‍♂️", name: "Man Standing"),
        Emoji(symbol: "🧍‍♀️", name: "Woman Standing"),
        Emoji(symbol: "🧎", name: "Person Kneeling"),
        Emoji(symbol: "🧎‍♂️", name: "Man Kneeling"),
        Emoji(symbol: "🧎‍♀️", name: "Woman Kneeling"),
        Emoji(symbol: "🧎‍➡️", name: "Person Kneeling Facing Right"),
        Emoji(symbol: "🧎‍♂️‍➡️", name: "Man Kneeling Facing Right"),
        Emoji(symbol: "🧎‍♀️‍➡️", name: "Woman Kneeling Facing Right"),
        Emoji(symbol: "🏃", name: "Person Running"),
        Emoji(symbol: "🏃‍♂️", name: "Man Running"),
        Emoji(symbol: "🏃‍♀️", name: "Woman Running"),
        Emoji(symbol: "🏃‍➡️", name: "Person Running Facing Right"),
        Emoji(symbol: "🏃‍♂️‍➡️", name: "Man Running Facing Right"),
        Emoji(symbol: "🏃‍♀️‍➡️", name: "Woman Running Facing Right"),
        // Family
        Emoji(symbol: "👫", name: "Woman and Man Holding Hands"),
        Emoji(symbol: "👬", name: "Men Holding Hands"),
        Emoji(symbol: "👭", name: "Women Holding Hands"),
        Emoji(symbol: "💑", name: "Couple With Heart"),
        Emoji(symbol: "💏", name: "Kiss"),
        Emoji(symbol: "👪", name: "Family"),
        Emoji(symbol: "👨‍👩‍👧", name: "Family: Man, Woman, Girl"),
        Emoji(symbol: "👨‍👩‍👧‍👦", name: "Family: Man, Woman, Girl, Boy"),
        Emoji(symbol: "👨‍👩‍👦‍👦", name: "Family: Man, Woman, Boy, Boy"),
        Emoji(symbol: "👨‍👩‍👧‍👧", name: "Family: Man, Woman, Girl, Girl"),
        Emoji(symbol: "👨‍👨‍👦", name: "Family: Man, Man, Boy"),
        Emoji(symbol: "👨‍👨‍👧", name: "Family: Man, Man, Girl"),
        Emoji(symbol: "👨‍👨‍👧‍👦", name: "Family: Man, Man, Girl, Boy"),
        Emoji(symbol: "👨‍👨‍👦‍👦", name: "Family: Man, Man, Boy, Boy"),
        Emoji(symbol: "👨‍👨‍👧‍👧", name: "Family: Man, Man, Girl, Girl"),
        Emoji(symbol: "👩‍👩‍👦", name: "Family: Woman, Woman, Boy"),
        Emoji(symbol: "👩‍👩‍👧", name: "Family: Woman, Woman, Girl"),
        Emoji(symbol: "👩‍👩‍👧‍👦", name: "Family: Woman, Woman, Girl, Boy"),
        Emoji(symbol: "👩‍👩‍👦‍👦", name: "Family: Woman, Woman, Boy, Boy"),
        Emoji(symbol: "👩‍👩‍👧‍👧", name: "Family: Woman, Woman, Girl, Girl"),
        Emoji(symbol: "👨‍👦", name: "Family: Man, Boy"),
        Emoji(symbol: "👨‍👦‍👦", name: "Family: Man, Boy, Boy"),
        Emoji(symbol: "👨‍👧", name: "Family: Man, Girl"),
        Emoji(symbol: "👨‍👧‍👦", name: "Family: Man, Girl, Boy"),
        Emoji(symbol: "👨‍👧‍👧", name: "Family: Man, Girl, Girl"),
        Emoji(symbol: "👩‍👦", name: "Family: Woman, Boy"),
        Emoji(symbol: "👩‍👦‍👦", name: "Family: Woman, Boy, Boy"),
        Emoji(symbol: "👩‍👧", name: "Family: Woman, Girl"),
        Emoji(symbol: "👩‍👧‍👦", name: "Family: Woman, Girl, Boy"),
        Emoji(symbol: "👩‍👧‍👧", name: "Family: Woman, Girl, Girl"),
        // Clothing
        Emoji(symbol: "🗣️", name: "Speaking Head"),
        Emoji(symbol: "👤", name: "Bust in Silhouette"),
        Emoji(symbol: "👥", name: "Busts in Silhouette"),
        Emoji(symbol: "🫂", name: "People Hugging"),
        Emoji(symbol: "👣", name: "Footprints")
    ]),
    EmojiCategory(name: "Animals & Nature",emojis: [
        Emoji(symbol: "🐶", name: "Dog Face"),
        Emoji(symbol: "🐱", name: "Cat Face"),
        Emoji(symbol: "🐭", name: "Mouse Face"),
        Emoji(symbol: "🐹", name: "Hamster Face"),
        Emoji(symbol: "🐰", name: "Rabbit Face"),
        Emoji(symbol: "🦊", name: "Fox"),
        Emoji(symbol: "🐻", name: "Bear"),
        Emoji(symbol: "🐼", name: "Panda"),
        Emoji(symbol: "🐻‍❄️", name: "Polar Bear"),
        Emoji(symbol: "🐨", name: "Koala"),
        Emoji(symbol: "🐯", name: "Tiger Face"),
        Emoji(symbol: "🦁", name: "Lion"),
        Emoji(symbol: "🐮", name: "Cow Face"),
        Emoji(symbol: "🐷", name: "Pig Face"),
        Emoji(symbol: "🐽", name: "Pig Nose"),
        Emoji(symbol: "🐸", name: "Frog"),
        Emoji(symbol: "🐵", name: "Monkey Face"),
        Emoji(symbol: "🙈", name: "See-No-Evil Monkey"),
        Emoji(symbol: "🙉", name: "Hear-No-Evil Monkey"),
        Emoji(symbol: "🙊", name: "Speak-No-Evil Monkey"),
        Emoji(symbol: "🐒", name: "Monkey"),
        Emoji(symbol: "🦍", name: "Gorilla"),
        Emoji(symbol: "🦧", name: "Orangutan"),
        Emoji(symbol: "🐕", name: "Dog"),
        Emoji(symbol: "🐕‍🦺", name: "Service Dog"),
        Emoji(symbol: "🐩", name: "Poodle"),
        Emoji(symbol: "🐺", name: "Wolf"),
        Emoji(symbol: "🦮", name: "Guide Dog"),
        Emoji(symbol: "🐈", name: "Cat"),
        Emoji(symbol: "🐈‍⬛", name: "Black Cat"),
        Emoji(symbol: "🦁", name: "Lion"),
        Emoji(symbol: "🐅", name: "Tiger"),
        Emoji(symbol: "🐆", name: "Leopard"),
        Emoji(symbol: "🐆", name: "Leopard"),
        Emoji(symbol: "🐴", name: "Horse Face"),
        Emoji(symbol: "🫎", name: "Moose"),
        Emoji(symbol: "🫏", name: "Donkey"),
        Emoji(symbol: "🐎", name: "Horse"),
        Emoji(symbol: "🦄", name: "Unicorn"),
        Emoji(symbol: "🦓", name: "Zebra"),
        Emoji(symbol: "🦌", name: "Deer"),
        Emoji(symbol: "🦬", name: "Bison"),
        Emoji(symbol: "🐄", name: "Cow"),
        Emoji(symbol: "🐂", name: "Ox"),
        Emoji(symbol: "🐃", name: "Water Buffalo"),
        Emoji(symbol: "🐋", name: "Whale"),
        Emoji(symbol: "🐳", name: "Spouting Whale"),
        Emoji(symbol: "🐟", name: "Fish"),
        Emoji(symbol: "🐠", name: "Tropical Fish"),
        Emoji(symbol: "🐡", name: "Blowfish"),
        Emoji(symbol: "🦈", name: "Shark"),
        Emoji(symbol: "🐙", name: "Octopus"),
        Emoji(symbol: "🐚", name: "Spiral Shell"),
        Emoji(symbol: "🪸", name: "Coral"),
        Emoji(symbol: "🪼", name: "Jellyfish"),
        // Birds
        Emoji(symbol: "🐦", name: "Bird"),
        Emoji(symbol: "🐤", name: "Baby Chick"),
        Emoji(symbol: "🐣", name: "Hatching Chick"),
        Emoji(symbol: "🐥", name: "Front-Facing Baby Chick"),
        Emoji(symbol: "🦆", name: "Duck"),
        Emoji(symbol: "🦅", name: "Eagle"),
        Emoji(symbol: "🦉", name: "Owl"),
        Emoji(symbol: "🦇", name: "Bat"),
        Emoji(symbol: "🪶", name: "Feather"),
        Emoji(symbol: "🦩", name: "Flamingo"),
        Emoji(symbol: "🦚", name: "Peacock"),
        Emoji(symbol: "🦜", name: "Parrot"),
        Emoji(symbol: "🪿", name: "Goose"),
        Emoji(symbol: "🐧", name: "Penguin"),
        Emoji(symbol: "🐔", name: "Chicken"),
        Emoji(symbol: "🐓", name: "Rooster"),
        Emoji(symbol: "🦃", name: "Turkey"),
        Emoji(symbol: "🕊️", name: "Dove"),
        Emoji(symbol: "🦤", name: "Dodo"),
        Emoji(symbol: "🦢", name: "Swan"),
        Emoji(symbol: "🦆", name: "Duck"),
        Emoji(symbol: "🪽", name: "Wing"),
        // Reptiles, amphibians, fish
        Emoji(symbol: "🐊", name: "Crocodile"),
        Emoji(symbol: "🐢", name: "Turtle"),
        Emoji(symbol: "🦎", name: "Lizard"),
        Emoji(symbol: "🐍", name: "Snake"),
        Emoji(symbol: "🐲", name: "Dragon Face"),
        Emoji(symbol: "🐉", name: "Dragon"),
        Emoji(symbol: "🦕", name: "Sauropod"),
        Emoji(symbol: "🦖", name: "T-Rex"),
        Emoji(symbol: "🦭", name: "Seal"),
        Emoji(symbol: "🐬", name: "Dolphin"),
        // Bugs
        Emoji(symbol: "🐛", name: "Bug"),
        Emoji(symbol: "🦋", name: "Butterfly"),
        Emoji(symbol: "🐌", name: "Snail"),
        Emoji(symbol: "🪱", name: "Worm"),
        Emoji(symbol: "🐞", name: "Lady Beetle"),
        Emoji(symbol: "🐜", name: "Ant"),
        Emoji(symbol: "🪲", name: "Beetle"),
        Emoji(symbol: "🦟", name: "Mosquito"),
        Emoji(symbol: "🪳", name: "Cockroach"),
        Emoji(symbol: "🪰", name: "Fly"),
        Emoji(symbol: "🐝", name: "Honeybee"),
        Emoji(symbol: "🐛", name: "Bug"),
        Emoji(symbol: "🦗", name: "Cricket"),
        Emoji(symbol: "🕷️", name: "Spider"),
        Emoji(symbol: "🕸️", name: "Spider Web"),
        Emoji(symbol: "🦂", name: "Scorpion"),
        // Sea creatures
        Emoji(symbol: "🦞", name: "Lobster"),
        Emoji(symbol: "🦀", name: "Crab"),
        Emoji(symbol: "🦐", name: "Shrimp"),
        Emoji(symbol: "🦑", name: "Squid"),
        Emoji(symbol: "🪼", name: "Jellyfish"),
        Emoji(symbol: "🦪", name: "Oyster"),
        // Extinct/Mythical
        Emoji(symbol: "🦣", name: "Mammoth"),
        Emoji(symbol: "🦴", name: "Bone"),
        // Animals body parts
        Emoji(symbol: "🐾", name: "Paw Prints"),
        // Plants
        Emoji(symbol: "🌵", name: "Cactus"),
        Emoji(symbol: "🎄", name: "Christmas Tree"),
        Emoji(symbol: "🌲", name: "Evergreen Tree"),
        Emoji(symbol: "🌳", name: "Deciduous Tree"),
        Emoji(symbol: "🌴", name: "Palm Tree"),
        Emoji(symbol: "🪴", name: "Potted Plant"),
        Emoji(symbol: "🪵", name: "Wood"),
        Emoji(symbol: "🌱", name: "Seedling"),
        Emoji(symbol: "🌿", name: "Herb"),
        Emoji(symbol: "☘️", name: "Shamrock"),
        Emoji(symbol: "🍀", name: "Four Leaf Clover"),
        Emoji(symbol: "🎍", name: "Pine Decoration"),
        Emoji(symbol: "🪴", name: "Potted Plant"),
        Emoji(symbol: "🎋", name: "Tanabata Tree"),
        Emoji(symbol: "🍃", name: "Leaf Fluttering in Wind"),
        Emoji(symbol: "🍂", name: "Fallen Leaves"),
        Emoji(symbol: "🍁", name: "Maple Leaf"),
        Emoji(symbol: "🪺", name: "Nest With Eggs"),
        Emoji(symbol: "🪶", name: "Feather"),
        // Flowers
        Emoji(symbol: "🌾", name: "Sheaf of Rice"),
        Emoji(symbol: "💐", name: "Bouquet"),
        Emoji(symbol: "🌷", name: "Tulip"),
        Emoji(symbol: "🌹", name: "Rose"),
        Emoji(symbol: "🥀", name: "Wilted Flower"),
        Emoji(symbol: "🪻", name: "Hyacinth"),
        Emoji(symbol: "🌺", name: "Hibiscus"),
        Emoji(symbol: "🌸", name: "Cherry Blossom"),
        Emoji(symbol: "🌼", name: "Blossom"),
        Emoji(symbol: "🌻", name: "Sunflower"),
        Emoji(symbol: "🌙", name: "Crescent Moon"),
        Emoji(symbol: "🌛", name: "First Quarter Moon Face"),
        Emoji(symbol: "🌜", name: "Last Quarter Moon Face"),
        Emoji(symbol: "🌚", name: "New Moon Face"),
        Emoji(symbol: "🌕", name: "Full Moon"),
        Emoji(symbol: "🌖", name: "Waning Gibbous Moon"),
        Emoji(symbol: "🌗", name: "Last Quarter Moon"),
        Emoji(symbol: "🌘", name: "Waning Crescent Moon"),
        Emoji(symbol: "🌑", name: "New Moon"),
        Emoji(symbol: "🌒", name: "Waxing Crescent Moon"),
        Emoji(symbol: "🌓", name: "First Quarter Moon"),
        Emoji(symbol: "🌔", name: "Waxing Gibbous Moon"),
        Emoji(symbol: "🌝", name: "Full Moon Face"),
        Emoji(symbol: "🌞", name: "Sun With Face"),
        Emoji(symbol: "🪐", name: "Ringed Planet"),
        Emoji(symbol: "⭐", name: "Star"),
        Emoji(symbol: "🌟", name: "Glowing Star"),
        Emoji(symbol: "🌠", name: "Shooting Star"),
        Emoji(symbol: "🌌", name: "Milky Way"),
        Emoji(symbol: "☀️", name: "Sun"),
        Emoji(symbol: "⛅", name: "Sun Behind Cloud"),
        Emoji(symbol: "⛈️", name: "Cloud With Lightning and Rain"),
        Emoji(symbol: "🌤️", name: "Sun Behind Small Cloud"),
        Emoji(symbol: "🌦️", name: "Sun Behind Rain Cloud"),
        Emoji(symbol: "🌧️", name: "Cloud With Rain"),
        Emoji(symbol: "🌩️", name: "Cloud With Lightning"),
        Emoji(symbol: "🌨️", name: "Cloud With Snow"),
        Emoji(symbol: "☁️", name: "Cloud"),
        Emoji(symbol: "💨", name: "Dashing Away"),
        Emoji(symbol: "☔", name: "Umbrella With Rain Drops"),
        Emoji(symbol: "💧", name: "Droplet"),
        Emoji(symbol: "💦", name: "Sweat Droplets"),
        Emoji(symbol: "🫧", name: "Bubbles"),
        Emoji(symbol: "☂️", name: "Umbrella"),
        Emoji(symbol: "🌊", name: "Water Wave"),
        Emoji(symbol: "❄️", name: "Snowflake"),
        Emoji(symbol: "☃️", name: "Snowman"),
        Emoji(symbol: "⛄", name: "Snowman Without Snow"),
        Emoji(symbol: "❄️", name: "Snowflake"),
        Emoji(symbol: "🌬️", name: "Wind Face"),
        Emoji(symbol: "💨", name: "Dashing Away"),
        Emoji(symbol: "💫", name: "Dizzy"),
        Emoji(symbol: "🌪️", name: "Tornado"),
        Emoji(symbol: "🌈", name: "Rainbow"),
        Emoji(symbol: "🌂", name: "Closed Umbrella"),
        Emoji(symbol: "☔", name: "Umbrella With Rain Drops"),
        Emoji(symbol: "⚡", name: "High Voltage"),
        Emoji(symbol: "❄️", name: "Snowflake"),
        Emoji(symbol: "☄️", name: "Comet"),
        Emoji(symbol: "🔥", name: "Fire"),
        Emoji(symbol: "💥", name: "Collision"),
        Emoji(symbol: "❄️", name: "Snowflake"),
        Emoji(symbol: "🌊", name: "Water Wave")
    ]),
    EmojiCategory(name: "Food & Drink",emojis: [
        // Fruits
        Emoji(symbol: "🍏", name: "Green Apple"),
        Emoji(symbol: "🍎", name: "Red Apple"),
        Emoji(symbol: "🍐", name: "Pear"),
        Emoji(symbol: "🍊", name: "Tangerine"),
        Emoji(symbol: "🍋", name: "Lemon"),
        Emoji(symbol: "🍌", name: "Banana"),
        Emoji(symbol: "🍉", name: "Watermelon"),
        Emoji(symbol: "🍇", name: "Grapes"),
        Emoji(symbol: "🍓", name: "Strawberry"),
        Emoji(symbol: "🫐", name: "Blueberries"),
        Emoji(symbol: "🍈", name: "Melon"),
        Emoji(symbol: "🍒", name: "Cherries"),
        Emoji(symbol: "🍑", name: "Peach"),
        Emoji(symbol: "🥭", name: "Mango"),
        Emoji(symbol: "🍍", name: "Pineapple"),
        Emoji(symbol: "🥥", name: "Coconut"),
        Emoji(symbol: "🥝", name: "Kiwi Fruit"),
        
        // Vegetables
        Emoji(symbol: "🍅", name: "Tomato"),
        Emoji(symbol: "🍆", name: "Eggplant"),
        Emoji(symbol: "🥑", name: "Avocado"),
        Emoji(symbol: "🥦", name: "Broccoli"),
        Emoji(symbol: "🥬", name: "Leafy Green"),
        Emoji(symbol: "🥒", name: "Cucumber"),
        Emoji(symbol: "🌶️", name: "Hot Pepper"),
        Emoji(symbol: "🫑", name: "Bell Pepper"),
        Emoji(symbol: "🌽", name: "Ear of Corn"),
        Emoji(symbol: "🥕", name: "Carrot"),
        Emoji(symbol: "🫒", name: "Olive"),
        Emoji(symbol: "🧄", name: "Garlic"),
        Emoji(symbol: "🧅", name: "Onion"),
        Emoji(symbol: "🥔", name: "Potato"),
        Emoji(symbol: "🍠", name: "Roasted Sweet Potato"),
        Emoji(symbol: "🫘", name: "Beans"),
        Emoji(symbol: "🥜", name: "Peanuts"),
        Emoji(symbol: "🌰", name: "Chestnut"),
        Emoji(symbol: "🫚", name: "Ginger"),
        Emoji(symbol: "🫛", name: "Pea Pod"),
        Emoji(symbol: "🥬", name: "Cabbage"),
        Emoji(symbol: "🌿", name: "Herb"),
        
        // Prepared food & Main dishes
        Emoji(symbol: "🍞", name: "Bread"),
        Emoji(symbol: "🥐", name: "Croissant"),
        Emoji(symbol: "🥖", name: "Baguette Bread"),
        Emoji(symbol: "🫓", name: "Flatbread"),
        Emoji(symbol: "🥨", name: "Pretzel"),
        Emoji(symbol: "🥯", name: "Bagel"),
        Emoji(symbol: "🥞", name: "Pancakes"),
        Emoji(symbol: "🧇", name: "Waffle"),
        Emoji(symbol: "🧀", name: "Cheese Wedge"),
        Emoji(symbol: "🍖", name: "Meat on Bone"),
        Emoji(symbol: "🍗", name: "Poultry Leg"),
        Emoji(symbol: "🥩", name: "Cut of Meat"),
        Emoji(symbol: "🥓", name: "Bacon"),
        Emoji(symbol: "🍔", name: "Hamburger"),
        Emoji(symbol: "🍟", name: "French Fries"),
        Emoji(symbol: "🍕", name: "Pizza"),
        Emoji(symbol: "🌭", name: "Hot Dog"),
        Emoji(symbol: "🥪", name: "Sandwich"),
        Emoji(symbol: "🌮", name: "Taco"),
        Emoji(symbol: "🌯", name: "Burrito"),
        Emoji(symbol: "🫔", name: "Tamale"),
        Emoji(symbol: "🥙", name: "Stuffed Flatbread"),
        Emoji(symbol: "🧆", name: "Falafel"),
        Emoji(symbol: "🥚", name: "Egg"),
        Emoji(symbol: "🍳", name: "Cooking"),
        Emoji(symbol: "🥘", name: "Shallow Pan of Food"),
        Emoji(symbol: "🍲", name: "Pot of Food"),
        Emoji(symbol: "🫕", name: "Fondue"),
        Emoji(symbol: "🥗", name: "Green Salad"),
        Emoji(symbol: "🍿", name: "Popcorn"),
        Emoji(symbol: "🧈", name: "Butter"),
        Emoji(symbol: "🧂", name: "Salt"),
        Emoji(symbol: "🥫", name: "Canned Food"),
        
        // Asian food
        Emoji(symbol: "🍱", name: "Bento Box"),
        Emoji(symbol: "🍘", name: "Rice Cracker"),
        Emoji(symbol: "🍙", name: "Rice Ball"),
        Emoji(symbol: "🍚", name: "Cooked Rice"),
        Emoji(symbol: "🍛", name: "Curry Rice"),
        Emoji(symbol: "🍜", name: "Steaming Bowl"),
        Emoji(symbol: "🍝", name: "Spaghetti"),
        Emoji(symbol: "🍢", name: "Oden"),
        Emoji(symbol: "🍣", name: "Sushi"),
        Emoji(symbol: "🍤", name: "Fried Shrimp"),
        Emoji(symbol: "🍥", name: "Fish Cake With Swirl"),
        Emoji(symbol: "🥮", name: "Moon Cake"),
        Emoji(symbol: "🍡", name: "Dango"),
        Emoji(symbol: "🥟", name: "Dumpling"),
        Emoji(symbol: "🥠", name: "Fortune Cookie"),
        Emoji(symbol: "🥡", name: "Takeout Box"),
        
        // Seafood (недоставало)
        Emoji(symbol: "🦐", name: "Shrimp"),
        Emoji(symbol: "🦞", name: "Lobster"),
        Emoji(symbol: "🦀", name: "Crab"),
        Emoji(symbol: "🐙", name: "Octopus"),
        Emoji(symbol: "🦑", name: "Squid"),
        Emoji(symbol: "🐠", name: "Tropical Fish"),
        Emoji(symbol: "🐟", name: "Fish"),
        Emoji(symbol: "🦈", name: "Shark"),
        
        // Desserts
        Emoji(symbol: "🍦", name: "Soft Ice Cream"),
        Emoji(symbol: "🍧", name: "Shaved Ice"),
        Emoji(symbol: "🍨", name: "Ice Cream"),
        Emoji(symbol: "🍩", name: "Doughnut"),
        Emoji(symbol: "🍪", name: "Cookie"),
        Emoji(symbol: "🎂", name: "Birthday Cake"),
        Emoji(symbol: "🍰", name: "Shortcake"),
        Emoji(symbol: "🧁", name: "Cupcake"),
        Emoji(symbol: "🥧", name: "Pie"),
        Emoji(symbol: "🍫", name: "Chocolate Bar"),
        Emoji(symbol: "🍬", name: "Candy"),
        Emoji(symbol: "🍭", name: "Lollipop"),
        Emoji(symbol: "🍮", name: "Custard"),
        Emoji(symbol: "🍯", name: "Honey Pot"),
        
        // Drinks - Hot beverages
        Emoji(symbol: "🍼", name: "Baby Bottle"),
        Emoji(symbol: "🥛", name: "Glass of Milk"),
        Emoji(symbol: "☕", name: "Hot Beverage"),
        Emoji(symbol: "🫖", name: "Teapot"),
        Emoji(symbol: "🍵", name: "Teacup Without Handle"),
        Emoji(symbol: "🫗", name: "Pouring Liquid"),
        
        // Drinks - Cold beverages (недоставало много)
        Emoji(symbol: "🥤", name: "Cup With Straw"),
        Emoji(symbol: "🧋", name: "Bubble Tea"),
        Emoji(symbol: "🧃", name: "Beverage Box"),
        Emoji(symbol: "🧉", name: "Mate"),
        Emoji(symbol: "🧊", name: "Ice"),
        
        // Alcoholic beverages (недоставало)
        Emoji(symbol: "🍶", name: "Sake"),
        Emoji(symbol: "🍺", name: "Beer Mug"),
        Emoji(symbol: "🍻", name: "Clinking Beer Mugs"),
        Emoji(symbol: "🥂", name: "Clinking Glasses"),
        Emoji(symbol: "🍷", name: "Wine Glass"),
        Emoji(symbol: "🥃", name: "Tumbler Glass"),
        Emoji(symbol: "🍸", name: "Cocktail Glass"),
        Emoji(symbol: "🍹", name: "Tropical Drink"),
        Emoji(symbol: "🍾", name: "Bottle With Popping Cork"),
        
        // Kitchen utensils (недоставало)
        Emoji(symbol: "🥄", name: "Spoon"),
        Emoji(symbol: "🍴", name: "Fork and Knife"),
        Emoji(symbol: "🥢", name: "Chopsticks"),
        Emoji(symbol: "🔪", name: "Kitchen Knife"),
        Emoji(symbol: "🫙", name: "Jar"),
        Emoji(symbol: "🏺", name: "Amphora")
    ]),
    EmojiCategory(name: "Activities", emojis: [
        // Sports with balls
        Emoji(symbol: "⚽", name: "Soccer Ball"),
        Emoji(symbol: "🏀", name: "Basketball"),
        Emoji(symbol: "🏈", name: "American Football"),
        Emoji(symbol: "⚾", name: "Baseball"),
        Emoji(symbol: "🥎", name: "Softball"),
        Emoji(symbol: "🎾", name: "Tennis"),
        Emoji(symbol: "🏐", name: "Volleyball"),
        Emoji(symbol: "🏉", name: "Rugby Football"),
        Emoji(symbol: "🎱", name: "Pool 8 Ball"),
        Emoji(symbol: "🏓", name: "Ping Pong"),
        Emoji(symbol: "🏸", name: "Badminton"),
        Emoji(symbol: "🥅", name: "Goal Net"),
        
        // Hockey and field sports
        Emoji(symbol: "🏒", name: "Ice Hockey"),
        Emoji(symbol: "🏑", name: "Field Hockey"),
        Emoji(symbol: "🏏", name: "Cricket Game"),
        Emoji(symbol: "🥍", name: "Lacrosse"),
        
        // Target and precision sports
        Emoji(symbol: "🏹", name: "Bow and Arrow"),
        Emoji(symbol: "🎣", name: "Fishing Pole"),
        Emoji(symbol: "🎯", name: "Direct Hit"),
        
        // Combat sports
        Emoji(symbol: "🥊", name: "Boxing Glove"),
        Emoji(symbol: "🥋", name: "Martial Arts Uniform"),
        Emoji(symbol: "🤺", name: "Fencer"),
        Emoji(symbol: "🤼", name: "Wrestlers"),
        
        // Athletics and fitness
        Emoji(symbol: "🎽", name: "Running Shirt"),
        Emoji(symbol: "🏋️‍♀️", name: "Weight Lifter"),
        Emoji(symbol: "🤸", name: "Person Cartwheeling"),
        Emoji(symbol: "⛹️", name: "Person Bouncing Ball"),
        Emoji(symbol: "🤾", name: "Person Playing Handball"),
        Emoji(symbol: "🏌️", name: "Person Golfing"),
        Emoji(symbol: "🏇", name: "Horse Racing"),
        
        // Water sports
        Emoji(symbol: "🏄", name: "Person Surfing"),
        Emoji(symbol: "🏊", name: "Person Swimming"),
        Emoji(symbol: "🤽", name: "Person Playing Water Polo"),
        Emoji(symbol: "🚣", name: "Person Rowing Boat"),
        Emoji(symbol: "🛶", name: "Canoe"),
        
        // Adventure and extreme sports
        Emoji(symbol: "🧗", name: "Person Climbing"),
        Emoji(symbol: "🚴", name: "Person Biking"),
        Emoji(symbol: "🚵", name: "Person Mountain Biking"),
        Emoji(symbol: "🛹", name: "Skateboard"),
        Emoji(symbol: "🛼", name: "Roller Skate"),
        Emoji(symbol: "⛸️", name: "Ice Skate"),
        Emoji(symbol: "🎿", name: "Skis"),
        Emoji(symbol: "⛷️", name: "Skier"),
        Emoji(symbol: "🏂", name: "Snowboarder"),
        Emoji(symbol: "🪂", name: "Parachute"),
        
        // Awards and achievements
        Emoji(symbol: "🥇", name: "1st Place Medal"),
        Emoji(symbol: "🥈", name: "2nd Place Medal"),
        Emoji(symbol: "🥉", name: "3rd Place Medal"),
        Emoji(symbol: "🏆", name: "Trophy"),
        Emoji(symbol: "🏅", name: "Sports Medal"),
        Emoji(symbol: "🎖️", name: "Military Medal"),
        Emoji(symbol: "🎗️", name: "Reminder Ribbon"),
        
        // Entertainment and tickets
        Emoji(symbol: "🎟️", name: "Admission Tickets"),
        Emoji(symbol: "🎫", name: "Ticket"),
        
        // Games and gaming
        Emoji(symbol: "🎮", name: "Controller"),
        Emoji(symbol: "🕹️", name: "Joystick"),
        Emoji(symbol: "🎰", name: "Slot Machine"),
        Emoji(symbol: "🎲", name: "Game Die"),
        Emoji(symbol: "🧩", name: "Puzzle Piece"),
        Emoji(symbol: "♟️", name: "Chess Pawn"),
        Emoji(symbol: "🎪", name: "Circus Tent"),
        Emoji(symbol: "🎭", name: "Performing Arts"),
        Emoji(symbol: "🎨", name: "Artist Palette"),
        
        // Music and performance
        Emoji(symbol: "🎼", name: "Musical Score"),
        Emoji(symbol: "🎵", name: "Musical Note"),
        Emoji(symbol: "🎶", name: "Musical Notes"),
        Emoji(symbol: "🎤", name: "Microphone"),
        Emoji(symbol: "🎧", name: "Headphone"),
        Emoji(symbol: "🎸", name: "Guitar"),
        Emoji(symbol: "🎹", name: "Musical Keyboard"),
        Emoji(symbol: "🎺", name: "Trumpet"),
        Emoji(symbol: "🎻", name: "Violin"),
        Emoji(symbol: "🪕", name: "Banjo"),
        Emoji(symbol: "🥁", name: "Drum"),
        Emoji(symbol: "🪘", name: "Long Drum"),
        Emoji(symbol: "🎷", name: "Saxophone"),
        Emoji(symbol: "🪗", name: "Accordion"),
        
        // Creative activities
        Emoji(symbol: "🖌️", name: "Paintbrush"),
        Emoji(symbol: "🖍️", name: "Crayon"),
        Emoji(symbol: "✏️", name: "Pencil"),
        Emoji(symbol: "🖊️", name: "Pen"),
        Emoji(symbol: "🖋️", name: "Fountain Pen"),
        
        // Additional recreational activities
        Emoji(symbol: "🎳", name: "Bowling"),
        Emoji(symbol: "🪩", name: "Mirror Ball"),
        Emoji(symbol: "🧸", name: "Teddy Bear"),
        Emoji(symbol: "🪀", name: "Yo-Yo"),
        Emoji(symbol: "🪁", name: "Kite"),
        Emoji(symbol: "🎊", name: "Confetti Ball"),
        Emoji(symbol: "🎉", name: "Party Popper")
    ]),
    EmojiCategory(name: "Travel & Places", emojis: [
        // Ground Vehicles
        Emoji(symbol: "🚗", name: "Car"),
        Emoji(symbol: "🚕", name: "Taxi"),
        Emoji(symbol: "🚙", name: "Sport Utility Vehicle"),
        Emoji(symbol: "🚌", name: "Bus"),
        Emoji(symbol: "🚎", name: "Trolleybus"),
        Emoji(symbol: "🏎️", name: "Racing Car"),
        Emoji(symbol: "🚓", name: "Police Car"),
        Emoji(symbol: "🚑", name: "Ambulance"),
        Emoji(symbol: "🚒", name: "Fire Engine"),
        Emoji(symbol: "🚐", name: "Minibus"),
        Emoji(symbol: "🚚", name: "Delivery Truck"),
        Emoji(symbol: "🚛", name: "Articulated Lorry"),
        Emoji(symbol: "🚜", name: "Tractor"),
        Emoji(symbol: "🛻", name: "Pickup Truck"),
        Emoji(symbol: "🛵", name: "Motor Scooter"),
        Emoji(symbol: "🏍️", name: "Motorcycle"),
        Emoji(symbol: "🚲", name: "Bicycle"),
        Emoji(symbol: "🛴", name: "Kick Scooter"),
        Emoji(symbol: "🚨", name: "Police Car Light"),
        Emoji(symbol: "🚔", name: "Oncoming Police Car"),
        Emoji(symbol: "🚍", name: "Oncoming Bus"),
        Emoji(symbol: "🚘", name: "Oncoming Automobile"),
        Emoji(symbol: "🚖", name: "Oncoming Taxi"),
        
        // Rail Vehicles
        Emoji(symbol: "🛤️", name: "Railway Track"),
        Emoji(symbol: "🚂", name: "Locomotive"),
        Emoji(symbol: "🚃", name: "Railway Car"),
        Emoji(symbol: "🚄", name: "High-Speed Train"),
        Emoji(symbol: "🚅", name: "Bullet Train"),
        Emoji(symbol: "🚆", name: "Train"),
        Emoji(symbol: "🚇", name: "Metro"),
        Emoji(symbol: "🚈", name: "Light Rail"),
        Emoji(symbol: "🚉", name: "Station"),
        Emoji(symbol: "🚊", name: "Tram"),
        Emoji(symbol: "🚝", name: "Monorail"),
        Emoji(symbol: "🚞", name: "Mountain Railway"),
        Emoji(symbol: "🚋", name: "Tram Car"),
        
        // Air Vehicles
        Emoji(symbol: "✈️", name: "Airplane"),
        Emoji(symbol: "🛫", name: "Airplane Departure"),
        Emoji(symbol: "🛬", name: "Airplane Arrival"),
        Emoji(symbol: "🪂", name: "Parachute"),
        Emoji(symbol: "💺", name: "Seat"),
        Emoji(symbol: "🛩️", name: "Small Airplane"),
        Emoji(symbol: "🛰️", name: "Satellite"),
        Emoji(symbol: "🚀", name: "Rocket"),
        Emoji(symbol: "🛸", name: "Flying Saucer"),
        Emoji(symbol: "🚁", name: "Helicopter"),
        
        // Water Vehicles
        Emoji(symbol: "⛵", name: "Sailboat"),
        Emoji(symbol: "🛶", name: "Canoe"),
        Emoji(symbol: "🚤", name: "Speedboat"),
        Emoji(symbol: "🛥️", name: "Motor Boat"),
        Emoji(symbol: "🛳️", name: "Passenger Ship"),
        Emoji(symbol: "⛴️", name: "Ferry"),
        Emoji(symbol: "🚢", name: "Ship"),
        Emoji(symbol: "⚓", name: "Anchor"),
        
        // Transport Infrastructure
        Emoji(symbol: "⛽", name: "Fuel Pump"),
        Emoji(symbol: "🚧", name: "Construction"),
        Emoji(symbol: "🚥", name: "Horizontal Traffic Light"),
        Emoji(symbol: "🚦", name: "Vertical Traffic Light"),
        Emoji(symbol: "🛑", name: "Stop Sign"),
        Emoji(symbol: "🛣️", name: "Motorway"),
        Emoji(symbol: "🛫", name: "Airplane Departure"),
        Emoji(symbol: "🛬", name: "Airplane Arrival"),
        
        // Buildings & Places
        Emoji(symbol: "🏰", name: "Castle"),
        Emoji(symbol: "🏯", name: "Japanese Castle"),
        Emoji(symbol: "🏟️", name: "Stadium"),
        Emoji(symbol: "🎡", name: "Ferris Wheel"),
        Emoji(symbol: "🎢", name: "Roller Coaster"),
        Emoji(symbol: "🎠", name: "Carousel Horse"),
        Emoji(symbol: "🗺️", name: "World Map"),
        Emoji(symbol: "🗿", name: "Moai"),
        Emoji(symbol: "🗽", name: "Statue of Liberty"),
        Emoji(symbol: "🗼", name: "Tokyo Tower"),
        Emoji(symbol: "🎪", name: "Circus Tent"),
        Emoji(symbol: "🎭", name: "Performing Arts"),
        
        // Geographic Features
        Emoji(symbol: "🌋", name: "Volcano"),
        Emoji(symbol: "🗻", name: "Mount Fuji"),
        Emoji(symbol: "🏔️", name: "Snow-Capped Mountain"),
        Emoji(symbol: "⛰️", name: "Mountain"),
        Emoji(symbol: "🏕️", name: "Camping"),
        Emoji(symbol: "🏖️", name: "Beach With Umbrella"),
        Emoji(symbol: "🏜️", name: "Desert"),
        Emoji(symbol: "🏝️", name: "Desert Island"),
        Emoji(symbol: "🏞️", name: "National Park"),
        
        // Urban Landscapes
        Emoji(symbol: "🏙️", name: "Cityscape"),
        Emoji(symbol: "🌆", name: "Cityscape at Dusk"),
        Emoji(symbol: "🌃", name: "Night With Stars"),
        Emoji(symbol: "🌉", name: "Bridge at Night"),
        Emoji(symbol: "🌁", name: "Foggy"),
        Emoji(symbol: "🌇", name: "Sunset"),
        
        // Additional Travel Items
        Emoji(symbol: "🧳", name: "Luggage"),
        Emoji(symbol: "⛱️", name: "Umbrella on Ground"),
        Emoji(symbol: "🎒", name: "Backpack"),
        Emoji(symbol: "🧭", name: "Compass"),
        Emoji(symbol: "🎫", name: "Ticket"),
        Emoji(symbol: "🎟️", name: "Admission Tickets"),
        Emoji(symbol: "🛂", name: "Passport Control"),
        Emoji(symbol: "🛃", name: "Customs"),
        Emoji(symbol: "🛄", name: "Baggage Claim"),
        Emoji(symbol: "🛅", name: "Left Luggage")
    ]),
    EmojiCategory(name: "Objects", emojis: [
        // Technology & Electronics
        Emoji(symbol: "⌚", name: "Watch"),
        Emoji(symbol: "📱", name: "Mobile Phone"),
        Emoji(symbol: "📲", name: "Mobile Phone With Arrow"),
        Emoji(symbol: "💻", name: "Laptop"),
        Emoji(symbol: "🖥️", name: "Desktop Computer"),
        Emoji(symbol: "🖨️", name: "Printer"),
        Emoji(symbol: "⌨️", name: "Keyboard"),
        Emoji(symbol: "🖱️", name: "Computer Mouse"),
        Emoji(symbol: "🖲️", name: "Trackball"),
        Emoji(symbol: "🕹️", name: "Joystick"),
        Emoji(symbol: "📟", name: "Pager"),
        Emoji(symbol: "📠", name: "Fax Machine"),
        Emoji(symbol: "☎️", name: "Telephone"),
        Emoji(symbol: "📞", name: "Telephone Receiver"),
        Emoji(symbol: "📺", name: "Television"),
        Emoji(symbol: "📻", name: "Radio"),
        Emoji(symbol: "🎙️", name: "Studio Microphone"),
        Emoji(symbol: "🎚️", name: "Level Slider"),
        Emoji(symbol: "🎛️", name: "Control Knobs"),
        Emoji(symbol: "📡", name: "Satellite Antenna"),
        Emoji(symbol: "🔋", name: "Battery"),
        Emoji(symbol: "🪫", name: "Low Battery"),
        Emoji(symbol: "🔌", name: "Electric Plug"),
        
        // Storage & Media
        Emoji(symbol: "💽", name: "Computer Disk"),
        Emoji(symbol: "💾", name: "Floppy Disk"),
        Emoji(symbol: "💿", name: "Optical Disk"),
        Emoji(symbol: "📀", name: "DVD"),
        Emoji(symbol: "🧮", name: "Abacus"),
        
        // Photography & Video
        Emoji(symbol: "📷", name: "Camera"),
        Emoji(symbol: "📸", name: "Camera With Flash"),
        Emoji(symbol: "📹", name: "Video Camera"),
        Emoji(symbol: "📼", name: "Videocassette"),
        Emoji(symbol: "🔍", name: "Magnifying Glass Tilted Left"),
        Emoji(symbol: "🔎", name: "Magnifying Glass Tilted Right"),
        Emoji(symbol: "🔬", name: "Microscope"),
        Emoji(symbol: "🔭", name: "Telescope"),
        
        // Lighting
        Emoji(symbol: "💡", name: "Light Bulb"),
        Emoji(symbol: "🔦", name: "Flashlight"),
        Emoji(symbol: "🏮", name: "Red Paper Lantern"),
        Emoji(symbol: "🪔", name: "Diya Lamp"),
        Emoji(symbol: "🕯️", name: "Candle"),
        
        // Books & Writing
        Emoji(symbol: "📔", name: "Notebook With Decorative Cover"),
        Emoji(symbol: "📕", name: "Closed Book"),
        Emoji(symbol: "📖", name: "Open Book"),
        Emoji(symbol: "📗", name: "Green Book"),
        Emoji(symbol: "📘", name: "Blue Book"),
        Emoji(symbol: "📙", name: "Orange Book"),
        Emoji(symbol: "📚", name: "Books"),
        Emoji(symbol: "📓", name: "Notebook"),
        Emoji(symbol: "📒", name: "Ledger"),
        Emoji(symbol: "📃", name: "Page With Curl"),
        Emoji(symbol: "📜", name: "Scroll"),
        Emoji(symbol: "📄", name: "Page Facing Up"),
        Emoji(symbol: "📰", name: "Newspaper"),
        Emoji(symbol: "🗞️", name: "Rolled-Up Newspaper"),
        Emoji(symbol: "📑", name: "Bookmark Tabs"),
        Emoji(symbol: "🔖", name: "Bookmark"),
        Emoji(symbol: "🏷️", name: "Label"),
        
        // Writing Tools
        Emoji(symbol: "📝", name: "Memo"),
        Emoji(symbol: "✏️", name: "Pencil"),
        Emoji(symbol: "✒️", name: "Black Nib"),
        Emoji(symbol: "🖋️", name: "Fountain Pen"),
        Emoji(symbol: "🖊️", name: "Pen"),
        Emoji(symbol: "🖌️", name: "Paintbrush"),
        Emoji(symbol: "🖍️", name: "Crayon"),
        
        // Office Supplies
        Emoji(symbol: "📎", name: "Paperclip"),
        Emoji(symbol: "🖇️", name: "Linked Paperclips"),
        Emoji(symbol: "📐", name: "Triangular Ruler"),
        Emoji(symbol: "📏", name: "Straight Ruler"),
        Emoji(symbol: "📌", name: "Pushpin"),
        Emoji(symbol: "📍", name: "Round Pushpin"),
        Emoji(symbol: "✂️", name: "Scissors"),
        Emoji(symbol: "🗃️", name: "Card File Box"),
        Emoji(symbol: "🗂️", name: "Card Index Dividers"),
        Emoji(symbol: "🗄️", name: "File Cabinet"),
        Emoji(symbol: "📋", name: "Clipboard"),
        Emoji(symbol: "📁", name: "File Folder"),
        Emoji(symbol: "📂", name: "Open File Folder"),
        Emoji(symbol: "🗒️", name: "Spiral Notepad"),
        Emoji(symbol: "🗓️", name: "Spiral Calendar"),
        Emoji(symbol: "📅", name: "Calendar"),
        Emoji(symbol: "📆", name: "Tear-Off Calendar"),
        
        // Tools & Equipment
        Emoji(symbol: "🗜️", name: "Clamp"),
        Emoji(symbol: "🔨", name: "Hammer"),
        Emoji(symbol: "⛏️", name: "Pick"),
        Emoji(symbol: "🪓", name: "Axe"),
        Emoji(symbol: "🛠️", name: "Hammer And Wrench"),
        Emoji(symbol: "🗡️", name: "Dagger"),
        Emoji(symbol: "⚔️", name: "Crossed Swords"),
        Emoji(symbol: "🔧", name: "Wrench"),
        Emoji(symbol: "🪛", name: "Screwdriver"),
        Emoji(symbol: "🔩", name: "Nut And Bolt"),
        Emoji(symbol: "⚙️", name: "Gear"),
        Emoji(symbol: "🪚", name: "Carpentry Saw"),
        Emoji(symbol: "⛓️", name: "Chains"),
        Emoji(symbol: "🪝", name: "Hook"),
        
        // Security & Safety
        Emoji(symbol: "🔒", name: "Locked"),
        Emoji(symbol: "🔓", name: "Unlocked"),
        Emoji(symbol: "🔏", name: "Locked With Pen"),
        Emoji(symbol: "🔐", name: "Locked With Key"),
        Emoji(symbol: "🗝️", name: "Old Key"),
        Emoji(symbol: "🔑", name: "Key"),
        Emoji(symbol: "🛡️", name: "Shield"),
        
        // Musical Instruments
        Emoji(symbol: "🎵", name: "Musical Note"),
        Emoji(symbol: "🎶", name: "Musical Notes"),
        Emoji(symbol: "🎼", name: "Musical Score"),
        Emoji(symbol: "🎹", name: "Musical Keyboard"),
        Emoji(symbol: "🥁", name: "Drum"),
        Emoji(symbol: "🪘", name: "Long Drum"),
        Emoji(symbol: "🎸", name: "Guitar"),
        Emoji(symbol: "🎺", name: "Trumpet"),
        Emoji(symbol: "🎷", name: "Saxophone"),
        Emoji(symbol: "🎻", name: "Violin"),
        Emoji(symbol: "🪕", name: "Banjo"),
        Emoji(symbol: "🪗", name: "Accordion"),
        Emoji(symbol: "🎤", name: "Microphone"),
        Emoji(symbol: "🎧", name: "Headphone"),
        
        // Household Items
        Emoji(symbol: "🛏️", name: "Bed"),
        Emoji(symbol: "🛋️", name: "Couch And Lamp"),
        Emoji(symbol: "🪑", name: "Chair"),
        Emoji(symbol: "🚿", name: "Shower"),
        Emoji(symbol: "🛁", name: "Bathtub"),
        Emoji(symbol: "🪤", name: "Mouse Trap"),
        Emoji(symbol: "🪒", name: "Razor"),
        Emoji(symbol: "🧴", name: "Lotion Bottle"),
        Emoji(symbol: "🧷", name: "Safety Pin"),
        Emoji(symbol: "🧹", name: "Broom"),
        Emoji(symbol: "🧺", name: "Basket"),
        Emoji(symbol: "🧻", name: "Roll of Paper"),
        Emoji(symbol: "🪣", name: "Bucket"),
        Emoji(symbol: "🧽", name: "Sponge"),
        Emoji(symbol: "🪥", name: "Toothbrush"),
        Emoji(symbol: "🧼", name: "Soap"),
        Emoji(symbol: "🪆", name: "Nesting Dolls"),
        
        // Kitchen & Dining
        Emoji(symbol: "🍽️", name: "Fork And Knife With Plate"),
        Emoji(symbol: "🔪", name: "Kitchen Knife"),
        Emoji(symbol: "🥄", name: "Spoon"),
        Emoji(symbol: "🍴", name: "Fork And Knife"),
        Emoji(symbol: "🥢", name: "Chopsticks"),
        Emoji(symbol: "🫖", name: "Teapot"),
        Emoji(symbol: "☕", name: "Hot Beverage"),
        Emoji(symbol: "🍵", name: "Teacup Without Handle"),
        Emoji(symbol: "🥃", name: "Tumbler Glass"),
        Emoji(symbol: "🍶", name: "Sake"),
        Emoji(symbol: "🍾", name: "Bottle With Popping Cork"),
        Emoji(symbol: "🍷", name: "Wine Glass"),
        Emoji(symbol: "🍸", name: "Cocktail Glass"),
        Emoji(symbol: "🍹", name: "Tropical Drink"),
        Emoji(symbol: "🍺", name: "Beer Mug"),
        Emoji(symbol: "🍻", name: "Clinking Beer Mugs"),
        Emoji(symbol: "🥂", name: "Clinking Glasses"),
        
        // Medical & Health
        Emoji(symbol: "💊", name: "Pill"),
        Emoji(symbol: "💉", name: "Syringe"),
        Emoji(symbol: "🩹", name: "Adhesive Bandage"),
        Emoji(symbol: "🩺", name: "Stethoscope"),
        Emoji(symbol: "🩼", name: "Crutch"),
        
        // Sports Equipment
        Emoji(symbol: "⚽", name: "Soccer Ball"),
        Emoji(symbol: "🏀", name: "Basketball"),
        Emoji(symbol: "🏈", name: "American Football"),
        Emoji(symbol: "⚾", name: "Baseball"),
        Emoji(symbol: "🥎", name: "Softball"),
        Emoji(symbol: "🎾", name: "Tennis"),
        Emoji(symbol: "🏐", name: "Volleyball"),
        Emoji(symbol: "🏉", name: "Rugby Football"),
        Emoji(symbol: "🥏", name: "Flying Disc"),
        Emoji(symbol: "🎳", name: "Bowling"),
        Emoji(symbol: "🏓", name: "Ping Pong"),
        Emoji(symbol: "🏸", name: "Badminton"),
        Emoji(symbol: "🥅", name: "Goal Net"),
        Emoji(symbol: "⛳", name: "Flag In Hole"),
        Emoji(symbol: "🪃", name: "Boomerang"),
        Emoji(symbol: "🥍", name: "Lacrosse"),
        Emoji(symbol: "🏑", name: "Field Hockey"),
        Emoji(symbol: "🏒", name: "Ice Hockey"),
        Emoji(symbol: "🥌", name: "Curling Stone"),
        Emoji(symbol: "🛷", name: "Sled"),
        Emoji(symbol: "⛷️", name: "Skier"),
        Emoji(symbol: "🎿", name: "Skis"),
        Emoji(symbol: "⛸️", name: "Ice Skate"),
        Emoji(symbol: "🥊", name: "Boxing Glove"),
        Emoji(symbol: "🥋", name: "Kimono"),
        Emoji(symbol: "👞", name: "Man's Shoe"),
        Emoji(symbol: "👟", name: "Running Shoe"),
        Emoji(symbol: "🥾", name: "Hiking Boot"),
        Emoji(symbol: "🥿", name: "Flat Shoe"),
        Emoji(symbol: "👠", name: "High-Heeled Shoe"),
        Emoji(symbol: "👡", name: "Woman's Sandal"),
        Emoji(symbol: "🩴", name: "Thong Sandal"),
        Emoji(symbol: "👢", name: "Woman's Boot"),
        Emoji(symbol: "🧦", name: "Socks"),
        Emoji(symbol: "🎁", name: "Wrapped Gift"),
        Emoji(symbol: "🎀", name: "Ribbon"),
        Emoji(symbol: "🎊", name: "Confetti Ball"),
        Emoji(symbol: "🎉", name: "Party Popper"),
        Emoji(symbol: "🎈", name: "Balloon"),
        Emoji(symbol: "🎂", name: "Birthday Cake"),
        Emoji(symbol: "🕰️", name: "Mantelpiece Clock"),
        Emoji(symbol: "⏰", name: "Alarm Clock"),
        Emoji(symbol: "⏱️", name: "Stopwatch"),
        Emoji(symbol: "⏲️", name: "Timer Clock"),
        Emoji(symbol: "🧳", name: "Luggage"),
        Emoji(symbol: "⛱️", name: "Umbrella On Ground"),
        Emoji(symbol: "☂️", name: "Umbrella"),
        Emoji(symbol: "💍", name: "Ring"),
        Emoji(symbol: "💎", name: "Gem Stone"),
        Emoji(symbol: "⚱️", name: "Funeral Urn"),
        Emoji(symbol: "🗿", name: "Moai"),
        Emoji(symbol: "🪬", name: "Hamsa"),
        Emoji(symbol: "🪩", name: "Mirror Ball"),
        Emoji(symbol: "🪭", name: "Folding Hand Fan")
    ]),
    EmojiCategory(name: "Symbols", emojis: [
        // Hearts
        Emoji(symbol: "❤️", name: "Red Heart"),
        Emoji(symbol: "🧡", name: "Orange Heart"),
        Emoji(symbol: "💛", name: "Yellow Heart"),
        Emoji(symbol: "💚", name: "Green Heart"),
        Emoji(symbol: "💙", name: "Blue Heart"),
        Emoji(symbol: "💜", name: "Purple Heart"),
        Emoji(symbol: "🖤", name: "Black Heart"),
        Emoji(symbol: "🤍", name: "White Heart"),
        Emoji(symbol: "🤎", name: "Brown Heart"),
        Emoji(symbol: "💔", name: "Broken Heart"),
        Emoji(symbol: "❣️", name: "Heart Exclamation"),
        Emoji(symbol: "💕", name: "Two Hearts"),
        Emoji(symbol: "💞", name: "Revolving Hearts"),
        Emoji(symbol: "💓", name: "Beating Heart"),
        Emoji(symbol: "💗", name: "Growing Heart"),
        Emoji(symbol: "💖", name: "Sparkling Heart"),
        Emoji(symbol: "💘", name: "Heart With Arrow"),
        Emoji(symbol: "💝", name: "Heart With Ribbon"),
        Emoji(symbol: "💟", name: "Heart Decoration"),
        
        // Punctuation and Exclamation
        Emoji(symbol: "❗", name: "Exclamation Mark"),
        Emoji(symbol: "❓", name: "Question Mark"),
        Emoji(symbol: "‼️", name: "Double Exclamation Mark"),
        Emoji(symbol: "⁉️", name: "Exclamation Question Mark"),
        Emoji(symbol: "❔", name: "White Question Mark"),
        Emoji(symbol: "❕", name: "White Exclamation Mark"),
        
        // Basic Shapes - Circles
        Emoji(symbol: "🔴", name: "Red Circle"),
        Emoji(symbol: "🟠", name: "Orange Circle"),
        Emoji(symbol: "🟡", name: "Yellow Circle"),
        Emoji(symbol: "🟢", name: "Green Circle"),
        Emoji(symbol: "🔵", name: "Blue Circle"),
        Emoji(symbol: "🟣", name: "Purple Circle"),
        Emoji(symbol: "🟤", name: "Brown Circle"),
        Emoji(symbol: "⚪", name: "White Circle"),
        Emoji(symbol: "⚫", name: "Black Circle"),
        
        // Basic Shapes - Squares
        Emoji(symbol: "🟥", name: "Red Square"),
        Emoji(symbol: "🟧", name: "Orange Square"),
        Emoji(symbol: "🟨", name: "Yellow Square"),
        Emoji(symbol: "🟩", name: "Green Square"),
        Emoji(symbol: "🟦", name: "Blue Square"),
        Emoji(symbol: "🟪", name: "Purple Square"),
        Emoji(symbol: "🟫", name: "Brown Square"),
        Emoji(symbol: "⬜", name: "White Large Square"),
        Emoji(symbol: "⬛", name: "Black Large Square"),
        Emoji(symbol: "◼️", name: "Black Medium Square"),
        Emoji(symbol: "◻️", name: "White Medium Square"),
        Emoji(symbol: "▪️", name: "Black Small Square"),
        Emoji(symbol: "▫️", name: "White Small Square"),
        
        // Triangles and Diamonds
        Emoji(symbol: "🔺", name: "Red Triangle Pointed Up"),
        Emoji(symbol: "🔻", name: "Red Triangle Pointed Down"),
        Emoji(symbol: "🔸", name: "Orange Diamond"),
        Emoji(symbol: "🔹", name: "Blue Diamond"),
        Emoji(symbol: "🔶", name: "Large Orange Diamond"),
        Emoji(symbol: "🔷", name: "Large Blue Diamond"),
        Emoji(symbol: "💠", name: "Diamond With Dot"),
        
        // Check marks and X marks
        Emoji(symbol: "✅", name: "Check Mark Button"),
        Emoji(symbol: "✔️", name: "Check Mark"),
        Emoji(symbol: "❌", name: "Cross Mark"),
        Emoji(symbol: "❎", name: "Cross Mark Button"),
        
        // Circles and buttons
        Emoji(symbol: "⭕", name: "Hollow Red Circle"),
        Emoji(symbol: "🔘", name: "Radio Button"),
        Emoji(symbol: "🔲", name: "Black Square Button"),
        Emoji(symbol: "🔳", name: "White Square Button"),
        
        // Mathematical and Logical Symbols
        Emoji(symbol: "➕", name: "Plus"),
        Emoji(symbol: "➖", name: "Minus"),
        Emoji(symbol: "➗", name: "Divide"),
        Emoji(symbol: "✖️", name: "Multiply"),
        Emoji(symbol: "🟰", name: "Heavy Equals Sign"),
        Emoji(symbol: "💯", name: "Hundred Points"),
        
        // Currency
        Emoji(symbol: "💲", name: "Dollar Sign"),
        Emoji(symbol: "💱", name: "Currency Exchange"),
        Emoji(symbol: "💹", name: "Chart Increasing With Yen"),
        
        // Stars and Sparkles
        Emoji(symbol: "⭐", name: "Star"),
        Emoji(symbol: "🌟", name: "Glowing Star"),
        Emoji(symbol: "✨", name: "Sparkles"),
        Emoji(symbol: "💫", name: "Dizzy"),
        Emoji(symbol: "⚡", name: "High Voltage"),
        Emoji(symbol: "🔥", name: "Fire"),
        Emoji(symbol: "💥", name: "Collision"),
        
        // Peace and Religious Symbols
        Emoji(symbol: "☮️", name: "Peace Symbol"),
        Emoji(symbol: "✝️", name: "Latin Cross"),
        Emoji(symbol: "☪️", name: "Star and Crescent"),
        Emoji(symbol: "🕉️", name: "Om"),
        Emoji(symbol: "☸️", name: "Wheel of Dharma"),
        Emoji(symbol: "✡️", name: "Star of David"),
        Emoji(symbol: "🔯", name: "Dotted Six-Pointed Star"),
        Emoji(symbol: "🕎", name: "Menorah"),
        Emoji(symbol: "☯️", name: "Yin Yang"),
        
        // Zodiac Signs
        Emoji(symbol: "♈", name: "Aries"),
        Emoji(symbol: "♉", name: "Taurus"),
        Emoji(symbol: "♊", name: "Gemini"),
        Emoji(symbol: "♋", name: "Cancer"),
        Emoji(symbol: "♌", name: "Leo"),
        Emoji(symbol: "♍", name: "Virgo"),
        Emoji(symbol: "♎", name: "Libra"),
        Emoji(symbol: "♏", name: "Scorpio"),
        Emoji(symbol: "♐", name: "Sagittarius"),
        Emoji(symbol: "♑", name: "Capricorn"),
        Emoji(symbol: "♒", name: "Aquarius"),
        Emoji(symbol: "♓", name: "Pisces"),
        Emoji(symbol: "⛎", name: "Ophiuchus"),
        
        // Gender Symbols
        Emoji(symbol: "♂️", name: "Male Sign"),
        Emoji(symbol: "♀️", name: "Female Sign"),
        Emoji(symbol: "⚧️", name: "Transgender Symbol"),
        
        // Medical and Warning
        Emoji(symbol: "⚕️", name: "Medical Symbol"),
        Emoji(symbol: "♻️", name: "Recycling Symbol"),
        Emoji(symbol: "⚠️", name: "Warning"),
        Emoji(symbol: "🚫", name: "Prohibited"),
        Emoji(symbol: "☢️", name: "Radioactive"),
        Emoji(symbol: "☣️", name: "Biohazard"),
        
        // Arrows
        Emoji(symbol: "⬆️", name: "Up Arrow"),
        Emoji(symbol: "↗️", name: "Up-Right Arrow"),
        Emoji(symbol: "➡️", name: "Right Arrow"),
        Emoji(symbol: "↘️", name: "Down-Right Arrow"),
        Emoji(symbol: "⬇️", name: "Down Arrow"),
        Emoji(symbol: "↙️", name: "Down-Left Arrow"),
        Emoji(symbol: "⬅️", name: "Left Arrow"),
        Emoji(symbol: "↖️", name: "Up-Left Arrow"),
        Emoji(symbol: "↕️", name: "Up-Down Arrow"),
        Emoji(symbol: "↔️", name: "Left-Right Arrow"),
        Emoji(symbol: "↩️", name: "Right Arrow Curving Left"),
        Emoji(symbol: "↪️", name: "Left Arrow Curving Right"),
        Emoji(symbol: "⤴️", name: "Right Arrow Curving Up"),
        Emoji(symbol: "⤵️", name: "Right Arrow Curving Down"),
        Emoji(symbol: "🔃", name: "Clockwise Vertical Arrows"),
        Emoji(symbol: "🔄", name: "Counterclockwise Arrows Button"),
        Emoji(symbol: "🔙", name: "Back Arrow"),
        Emoji(symbol: "🔚", name: "End Arrow"),
        Emoji(symbol: "🔛", name: "On Arrow"),
        Emoji(symbol: "🔜", name: "Soon Arrow"),
        Emoji(symbol: "🔝", name: "Top Arrow"),
        
        // Information and Symbols
        Emoji(symbol: "ℹ️", name: "Information"),
        Emoji(symbol: "🔤", name: "Input Latin Letters"),
        Emoji(symbol: "🔡", name: "Input Latin Lowercase"),
        Emoji(symbol: "🔠", name: "Input Latin Uppercase"),
        Emoji(symbol: "🔢", name: "Input Numbers"),
        Emoji(symbol: "🔣", name: "Input Symbols"),
        Emoji(symbol: "#️⃣", name: "Keycap Number Sign"),
        Emoji(symbol: "*️⃣", name: "Keycap Asterisk"),
        Emoji(symbol: "0️⃣", name: "Keycap Digit Zero"),
        Emoji(symbol: "1️⃣", name: "Keycap Digit One"),
        Emoji(symbol: "2️⃣", name: "Keycap Digit Two"),
        Emoji(symbol: "3️⃣", name: "Keycap Digit Three"),
        Emoji(symbol: "4️⃣", name: "Keycap Digit Four"),
        Emoji(symbol: "5️⃣", name: "Keycap Digit Five"),
        Emoji(symbol: "6️⃣", name: "Keycap Digit Six"),
        Emoji(symbol: "7️⃣", name: "Keycap Digit Seven"),
        Emoji(symbol: "8️⃣", name: "Keycap Digit Eight"),
        Emoji(symbol: "9️⃣", name: "Keycap Digit Nine"),
        Emoji(symbol: "🔟", name: "Keycap 10"),
        
        // Copyright and Trademark
        Emoji(symbol: "©️", name: "Copyright"),
        Emoji(symbol: "®️", name: "Registered"),
        Emoji(symbol: "™️", name: "Trade Mark"),
        
        // Media Controls
        Emoji(symbol: "⏸️", name: "Pause Button"),
        Emoji(symbol: "⏹️", name: "Stop Button"),
        Emoji(symbol: "⏺️", name: "Record Button"),
        Emoji(symbol: "⏭️", name: "Next Track Button"),
        Emoji(symbol: "⏮️", name: "Previous Track Button"),
        Emoji(symbol: "⏯️", name: "Play or Pause Button"),
        Emoji(symbol: "⏪", name: "Fast Reverse Button"),
        Emoji(symbol: "⏩", name: "Fast-Forward Button"),
        Emoji(symbol: "⏫", name: "Fast Up Button"),
        Emoji(symbol: "⏬", name: "Fast Down Button"),
        Emoji(symbol: "🔀", name: "Shuffle Tracks Button"),
        Emoji(symbol: "🔁", name: "Repeat Button"),
        Emoji(symbol: "🔂", name: "Repeat Single Button"),
        
        // Volume Controls
        Emoji(symbol: "🔇", name: "Muted Speaker"),
        Emoji(symbol: "🔈", name: "Speaker Low Volume"),
        Emoji(symbol: "🔉", name: "Speaker Medium Volume"),
        Emoji(symbol: "🔊", name: "Speaker High Volume"),
        
        // Miscellaneous Symbols
        Emoji(symbol: "🆔", name: "ID Button"),
        Emoji(symbol: "🈳", name: "Japanese \"Vacancy\" Button"),
        Emoji(symbol: "🈂️", name: "Japanese \"Service Charge\" Button"),
        Emoji(symbol: "🆚", name: "VS Button"),
        Emoji(symbol: "🆕", name: "NEW Button"),
        Emoji(symbol: "🆓", name: "FREE Button"),
        Emoji(symbol: "🆙", name: "UP! Button"),
        Emoji(symbol: "🆗", name: "OK Button"),
        Emoji(symbol: "🆒", name: "COOL Button"),
        Emoji(symbol: "🈶", name: "Japanese \"Not Free of Charge\" Button"),
        Emoji(symbol: "🈹", name: "Japanese \"Discount\" Button"),
        Emoji(symbol: "🈯", name: "Japanese \"Reserved\" Button"),
        Emoji(symbol: "🉐", name: "Japanese \"Bargain\" Button"),
        Emoji(symbol: "🈴", name: "Japanese \"Passing Grade\" Button"),
        Emoji(symbol: "🈲", name: "Japanese \"Prohibited\" Button"),
        Emoji(symbol: "🅰️", name: "A Button (Blood Type)"),
        Emoji(symbol: "🅱️", name: "B Button (Blood Type)"),
        Emoji(symbol: "🆎", name: "AB Button (Blood Type)"),
        Emoji(symbol: "🅾️", name: "O Button (Blood Type)"),
        Emoji(symbol: "🈺", name: "Japanese \"Open for Business\" Button"),
    ]),
    EmojiCategory(name: "Buildings", emojis: [
        Emoji(symbol: "🏠", name: "House"),
        Emoji(symbol: "🏡", name: "House With Garden"),
        Emoji(symbol: "🏘️", name: "Housing Complex"),
        Emoji(symbol: "🏚️", name: "Derelict House"),
        Emoji(symbol: "🏗️", name: "Building Construction"),
        Emoji(symbol: "🏢", name: "Office Building"),
        Emoji(symbol: "🏬", name: "Department Store"),
        Emoji(symbol: "🏣", name: "Japanese Post Office"),
        Emoji(symbol: "🏤", name: "Post Office"),
        Emoji(symbol: "🏥", name: "Hospital"),
        Emoji(symbol: "🏦", name: "Bank"),
        Emoji(symbol: "🏨", name: "Hotel"),
        Emoji(symbol: "🏪", name: "Convenience Store"),
        Emoji(symbol: "🏫", name: "School"),
        Emoji(symbol: "🏛️", name: "Classical Building"),
        Emoji(symbol: "🏰", name: "Castle"),
        Emoji(symbol: "🕍", name: "Synagogue"),
        Emoji(symbol: "⛪️", name: "Church"),
        Emoji(symbol: "🕌", name: "Mosque"),
        Emoji(symbol: "🛕", name: "Hindu Temple"),
        Emoji(symbol: "🕋", name: "Kaaba"),
    ]),
    EmojiCategory(name: "Flags", emojis: [
        Emoji(symbol: "🇦🇫", name: "Flag: Afghanistan"),
        Emoji(symbol: "🇦🇽", name: "Flag: Åland Islands"),
        Emoji(symbol: "🇦🇱", name: "Flag: Albania"),
        Emoji(symbol: "🇩🇿", name: "Flag: Algeria"),
        Emoji(symbol: "🇦🇸", name: "Flag: American Samoa"),
        Emoji(symbol: "🇦🇩", name: "Flag: Andorra"),
        Emoji(symbol: "🇦🇴", name: "Flag: Angola"),
        Emoji(symbol: "🇦🇮", name: "Flag: Anguilla"),
        Emoji(symbol: "🇦🇶", name: "Flag: Antarctica"),
        Emoji(symbol: "🇦🇬", name: "Flag: Antigua & Barbuda"),
        Emoji(symbol: "🇦🇷", name: "Flag: Argentina"),
        Emoji(symbol: "🇦🇲", name: "Flag: Armenia"),
        Emoji(symbol: "🇦🇼", name: "Flag: Aruba"),
        Emoji(symbol: "🇦🇨", name: "Flag: Ascension Island"),
        Emoji(symbol: "🇦🇺", name: "Flag: Australia"),
        Emoji(symbol: "🇦🇹", name: "Flag: Austria"),
        Emoji(symbol: "🇦🇿", name: "Flag: Azerbaijan"),
        Emoji(symbol: "🇧🇸", name: "Flag: Bahamas"),
        Emoji(symbol: "🇧🇭", name: "Flag: Bahrain"),
        Emoji(symbol: "🇧🇩", name: "Flag: Bangladesh"),
        Emoji(symbol: "🇧🇧", name: "Flag: Barbados"),
        Emoji(symbol: "🇧🇾", name: "Flag: Belarus"),
        Emoji(symbol: "🇧🇪", name: "Flag: Belgium"),
        Emoji(symbol: "🇧🇿", name: "Flag: Belize"),
        Emoji(symbol: "🇧🇯", name: "Flag: Benin"),
        Emoji(symbol: "🇧🇲", name: "Flag: Bermuda"),
        Emoji(symbol: "🇧🇹", name: "Flag: Bhutan"),
        Emoji(symbol: "🇧🇴", name: "Flag: Bolivia"),
        Emoji(symbol: "🇧🇶", name: "Flag: Caribbean Netherlands"),
        Emoji(symbol: "🇧🇦", name: "Flag: Bosnia & Herzegovina"),
        Emoji(symbol: "🇧🇼", name: "Flag: Botswana"),
        Emoji(symbol: "🇧🇻", name: "Flag: Bouvet Island"),
        Emoji(symbol: "🇧🇷", name: "Flag: Brazil"),
        Emoji(symbol: "🇮🇴", name: "Flag: British Indian Ocean Territory"),
        Emoji(symbol: "🇻🇬", name: "Flag: British Virgin Islands"),
        Emoji(symbol: "🇧🇳", name: "Flag: Brunei"),
        Emoji(symbol: "🇧🇬", name: "Flag: Bulgaria"),
        Emoji(symbol: "🇧🇫", name: "Flag: Burkina Faso"),
        Emoji(symbol: "🇧🇮", name: "Flag: Burundi"),
        Emoji(symbol: "🇨🇻", name: "Flag: Cabo Verde"),
        Emoji(symbol: "🇰🇭", name: "Flag: Cambodia"),
        Emoji(symbol: "🇨🇲", name: "Flag: Cameroon"),
        Emoji(symbol: "🇨🇦", name: "Flag: Canada"),
        Emoji(symbol: "🇮🇨", name: "Flag: Canary Islands"),
        Emoji(symbol: "🇰🇾", name: "Flag: Cayman Islands"),
        Emoji(symbol: "🇨🇫", name: "Flag: Central African Republic"),
        Emoji(symbol: "🇪🇦", name: "Flag: Ceuta & Melilla"),
        Emoji(symbol: "🇹🇩", name: "Flag: Chad"),
        Emoji(symbol: "🇨🇱", name: "Flag: Chile"),
        Emoji(symbol: "🇨🇳", name: "Flag: China"),
        Emoji(symbol: "🇨🇽", name: "Flag: Christmas Island"),
        Emoji(symbol: "🇨🇵", name: "Flag: Clipperton Island"),
        Emoji(symbol: "🇨🇨", name: "Flag: Cocos (Keeling) Islands"),
        Emoji(symbol: "🇨🇴", name: "Flag: Colombia"),
        Emoji(symbol: "🇰🇲", name: "Flag: Comoros"),
        Emoji(symbol: "🇨🇬", name: "Flag: Congo - Brazzaville"),
        Emoji(symbol: "🇨🇩", name: "Flag: Congo - Kinshasa"),
        Emoji(symbol: "🇨🇰", name: "Flag: Cook Islands"),
        Emoji(symbol: "🇨🇷", name: "Flag: Costa Rica"),
        Emoji(symbol: "🇨🇮", name: "Flag: Côte d'Ivoire"),
        Emoji(symbol: "🇭🇷", name: "Flag: Croatia"),
        Emoji(symbol: "🇨🇺", name: "Flag: Cuba"),
        Emoji(symbol: "🇨🇼", name: "Flag: Curaçao"),
        Emoji(symbol: "🇨🇾", name: "Flag: Cyprus"),
        Emoji(symbol: "🇨🇿", name: "Flag: Czechia"),
        Emoji(symbol: "🇩🇰", name: "Flag: Denmark"),
        Emoji(symbol: "🇩🇬", name: "Flag: Diego Garcia"),
        Emoji(symbol: "🇩🇯", name: "Flag: Djibouti"),
        Emoji(symbol: "🇩🇲", name: "Flag: Dominica"),
        Emoji(symbol: "🇩🇴", name: "Flag: Dominican Republic"),
        Emoji(symbol: "🇪🇨", name: "Flag: Ecuador"),
        Emoji(symbol: "🇪🇬", name: "Flag: Egypt"),
        Emoji(symbol: "🇸🇻", name: "Flag: El Salvador"),
        Emoji(symbol: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", name: "Flag: England"),
        Emoji(symbol: "🇬🇶", name: "Flag: Equatorial Guinea"),
        Emoji(symbol: "🇪🇷", name: "Flag: Eritrea"),
        Emoji(symbol: "🇪🇪", name: "Flag: Estonia"),
        Emoji(symbol: "🇸🇿", name: "Flag: Eswatini"),
        Emoji(symbol: "🇪🇹", name: "Flag: Ethiopia"),
        Emoji(symbol: "🇪🇺", name: "Flag: European Union"),
        Emoji(symbol: "🇫🇰", name: "Flag: Falkland Islands"),
        Emoji(symbol: "🇫🇴", name: "Flag: Faroe Islands"),
        Emoji(symbol: "🇫🇯", name: "Flag: Fiji"),
        Emoji(symbol: "🇫🇮", name: "Flag: Finland"),
        Emoji(symbol: "🇫🇷", name: "Flag: France"),
        Emoji(symbol: "🇬🇫", name: "Flag: French Guiana"),
        Emoji(symbol: "🇵🇫", name: "Flag: French Polynesia"),
        Emoji(symbol: "🇹🇫", name: "Flag: French Southern Territories"),
        Emoji(symbol: "🇬🇦", name: "Flag: Gabon"),
        Emoji(symbol: "🇬🇲", name: "Flag: Gambia"),
        Emoji(symbol: "🇬🇪", name: "Flag: Georgia"),
        Emoji(symbol: "🇩🇪", name: "Flag: Germany"),
        Emoji(symbol: "🇬🇭", name: "Flag: Ghana"),
        Emoji(symbol: "🇬🇮", name: "Flag: Gibraltar"),
        Emoji(symbol: "🇬🇷", name: "Flag: Greece"),
        Emoji(symbol: "🇬🇱", name: "Flag: Greenland"),
        Emoji(symbol: "🇬🇩", name: "Flag: Grenada"),
        Emoji(symbol: "🇬🇵", name: "Flag: Guadeloupe"),
        Emoji(symbol: "🇬🇺", name: "Flag: Guam"),
        Emoji(symbol: "🇬🇹", name: "Flag: Guatemala"),
        Emoji(symbol: "🇬🇬", name: "Flag: Guernsey"),
        Emoji(symbol: "🇬🇳", name: "Flag: Guinea"),
        Emoji(symbol: "🇬🇼", name: "Flag: Guinea-Bissau"),
        Emoji(symbol: "🇬🇾", name: "Flag: Guyana"),
        Emoji(symbol: "🇭🇹", name: "Flag: Haiti"),
        Emoji(symbol: "🇭🇲", name: "Flag: Heard & McDonald Islands"),
        Emoji(symbol: "🇭🇳", name: "Flag: Honduras"),
        Emoji(symbol: "🇭🇰", name: "Flag: Hong Kong SAR China"),
        Emoji(symbol: "🇭🇺", name: "Flag: Hungary"),
        Emoji(symbol: "🇮🇸", name: "Flag: Iceland"),
        Emoji(symbol: "🇮🇳", name: "Flag: India"),
        Emoji(symbol: "🇮🇩", name: "Flag: Indonesia"),
        Emoji(symbol: "🇮🇷", name: "Flag: Iran"),
        Emoji(symbol: "🇮🇶", name: "Flag: Iraq"),
        Emoji(symbol: "🇮🇪", name: "Flag: Ireland"),
        Emoji(symbol: "🇮🇲", name: "Flag: Isle of Man"),
        Emoji(symbol: "🇮🇱", name: "Flag: Israel"),
        Emoji(symbol: "🇮🇹", name: "Flag: Italy"),
        Emoji(symbol: "🇯🇲", name: "Flag: Jamaica"),
        Emoji(symbol: "🇯🇵", name: "Flag: Japan"),
        Emoji(symbol: "🇯🇪", name: "Flag: Jersey"),
        Emoji(symbol: "🇯🇴", name: "Flag: Jordan"),
        Emoji(symbol: "🇰🇿", name: "Flag: Kazakhstan"),
        Emoji(symbol: "🇰🇪", name: "Flag: Kenya"),
        Emoji(symbol: "🇰🇮", name: "Flag: Kiribati"),
        Emoji(symbol: "🇽🇰", name: "Flag: Kosovo"),
        Emoji(symbol: "🇰🇼", name: "Flag: Kuwait"),
        Emoji(symbol: "🇰🇬", name: "Flag: Kyrgyzstan"),
        Emoji(symbol: "🇱🇦", name: "Flag: Laos"),
        Emoji(symbol: "🇱🇻", name: "Flag: Latvia"),
        Emoji(symbol: "🇱🇧", name: "Flag: Lebanon"),
        Emoji(symbol: "🇱🇸", name: "Flag: Lesotho"),
        Emoji(symbol: "🇱🇷", name: "Flag: Liberia"),
        Emoji(symbol: "🇱🇾", name: "Flag: Libya"),
        Emoji(symbol: "🇱🇮", name: "Flag: Liechtenstein"),
        Emoji(symbol: "🇱🇹", name: "Flag: Lithuania"),
        Emoji(symbol: "🇱🇺", name: "Flag: Luxembourg"),
        Emoji(symbol: "🇲🇴", name: "Flag: Macao SAR China"),
        Emoji(symbol: "🇲🇬", name: "Flag: Madagascar"),
        Emoji(symbol: "🇲🇼", name: "Flag: Malawi"),
        Emoji(symbol: "🇲🇾", name: "Flag: Malaysia"),
        Emoji(symbol: "🇲🇻", name: "Flag: Maldives"),
        Emoji(symbol: "🇲🇱", name: "Flag: Mali"),
        Emoji(symbol: "🇲🇹", name: "Flag: Malta"),
        Emoji(symbol: "🇲🇭", name: "Flag: Marshall Islands"),
        Emoji(symbol: "🇲🇶", name: "Flag: Martinique"),
        Emoji(symbol: "🇲🇷", name: "Flag: Mauritania"),
        Emoji(symbol: "🇲🇺", name: "Flag: Mauritius"),
        Emoji(symbol: "🇾🇹", name: "Flag: Mayotte"),
        Emoji(symbol: "🇲🇽", name: "Flag: Mexico"),
        Emoji(symbol: "🇫🇲", name: "Flag: Micronesia"),
        Emoji(symbol: "🇲🇩", name: "Flag: Moldova"),
        Emoji(symbol: "🇲🇨", name: "Flag: Monaco"),
        Emoji(symbol: "🇲🇳", name: "Flag: Mongolia"),
        Emoji(symbol: "🇲🇪", name: "Flag: Montenegro"),
        Emoji(symbol: "🇲🇸", name: "Flag: Montserrat"),
        Emoji(symbol: "🇲🇦", name: "Flag: Morocco"),
        Emoji(symbol: "🇲🇿", name: "Flag: Mozambique"),
        Emoji(symbol: "🇲🇲", name: "Flag: Myanmar (Burma)"),
        Emoji(symbol: "🇳🇦", name: "Flag: Namibia"),
        Emoji(symbol: "🇳🇷", name: "Flag: Nauru"),
        Emoji(symbol: "🇳🇵", name: "Flag: Nepal"),
        Emoji(symbol: "🇳🇱", name: "Flag: Netherlands"),
        Emoji(symbol: "🇳🇨", name: "Flag: New Caledonia"),
        Emoji(symbol: "🇳🇿", name: "Flag: New Zealand"),
        Emoji(symbol: "🇳🇮", name: "Flag: Nicaragua"),
        Emoji(symbol: "🇳🇪", name: "Flag: Niger"),
        Emoji(symbol: "🇳🇬", name: "Flag: Nigeria"),
        Emoji(symbol: "🇳🇺", name: "Flag: Niue"),
        Emoji(symbol: "🇳🇫", name: "Flag: Norfolk Island"),
        Emoji(symbol: "🇲🇰", name: "Flag: North Macedonia"),
        Emoji(symbol: "🇲🇵", name: "Flag: Northern Mariana Islands"),
        Emoji(symbol: "🇰🇵", name: "Flag: North Korea"),
        Emoji(symbol: "🇳🇴", name: "Flag: Norway"),
        Emoji(symbol: "🇴🇲", name: "Flag: Oman"),
        Emoji(symbol: "🇵🇰", name: "Flag: Pakistan"),
        Emoji(symbol: "🇵🇼", name: "Flag: Palau"),
        Emoji(symbol: "🇵🇸", name: "Flag: Palestinian Territories"),
        Emoji(symbol: "🇵🇦", name: "Flag: Panama"),
        Emoji(symbol: "🇵🇬", name: "Flag: Papua New Guinea"),
        Emoji(symbol: "🇵🇾", name: "Flag: Paraguay"),
        Emoji(symbol: "🇵🇪", name: "Flag: Peru"),
        Emoji(symbol: "🇵🇭", name: "Flag: Philippines"),
        Emoji(symbol: "🇵🇳", name: "Flag: Pitcairn Islands"),
        Emoji(symbol: "🇵🇱", name: "Flag: Poland"),
        Emoji(symbol: "🇵🇹", name: "Flag: Portugal"),
        Emoji(symbol: "🇵🇷", name: "Flag: Puerto Rico"),
        Emoji(symbol: "🇶🇦", name: "Flag: Qatar"),
        Emoji(symbol: "🇷🇪", name: "Flag: Réunion"),
        Emoji(symbol: "🇷🇴", name: "Flag: Romania"),
        Emoji(symbol: "🇷🇺", name: "Flag: Russia"),
        Emoji(symbol: "🇷🇼", name: "Flag: Rwanda"),
        Emoji(symbol: "🇼🇸", name: "Flag: Samoa"),
        Emoji(symbol: "🇸🇲", name: "Flag: San Marino"),
        Emoji(symbol: "🇸🇹", name: "Flag: São Tomé & Príncipe"),
        Emoji(symbol: "🇸🇦", name: "Flag: Saudi Arabia"),
        Emoji(symbol: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", name: "Flag: Scotland"),
        Emoji(symbol: "🇸🇳", name: "Flag: Senegal"),
        Emoji(symbol: "🇷🇸", name: "Flag: Serbia"),
        Emoji(symbol: "🇸🇨", name: "Flag: Seychelles"),
        Emoji(symbol: "🇸🇱", name: "Flag: Sierra Leone"),
        Emoji(symbol: "🇸🇬", name: "Flag: Singapore"),
        Emoji(symbol: "🇸🇽", name: "Flag: Sint Maarten"),
        Emoji(symbol: "🇸🇰", name: "Flag: Slovakia"),
        Emoji(symbol: "🇸🇮", name: "Flag: Slovenia"),
        Emoji(symbol: "🇸🇧", name: "Flag: Solomon Islands"),
        Emoji(symbol: "🇸🇴", name: "Flag: Somalia"),
        Emoji(symbol: "🇿🇦", name: "Flag: South Africa"),
        Emoji(symbol: "🇬🇸", name: "Flag: South Georgia & South Sandwich Islands"),
        Emoji(symbol: "🇰🇷", name: "Flag: South Korea"),
        Emoji(symbol: "🇸🇸", name: "Flag: South Sudan"),
        Emoji(symbol: "🇪🇸", name: "Flag: Spain"),
        Emoji(symbol: "🇱🇰", name: "Flag: Sri Lanka"),
        Emoji(symbol: "🇧🇱", name: "Flag: St. Barthélemy"),
        Emoji(symbol: "🇸🇭", name: "Flag: St. Helena"),
        Emoji(symbol: "🇰🇳", name: "Flag: St. Kitts & Nevis"),
        Emoji(symbol: "🇱🇨", name: "Flag: St. Lucia"),
        Emoji(symbol: "🇲🇫", name: "Flag: St. Martin"),
        Emoji(symbol: "🇵🇲", name: "Flag: St. Pierre & Miquelon"),
        Emoji(symbol: "🇻🇨", name: "Flag: St. Vincent & Grenadines"),
        Emoji(symbol: "🇸🇩", name: "Flag: Sudan"),
        Emoji(symbol: "🇸🇷", name: "Flag: Suriname"),
        Emoji(symbol: "🇸🇯", name: "Flag: Svalbard & Jan Mayen"),
        Emoji(symbol: "🇸🇪", name: "Flag: Sweden"),
        Emoji(symbol: "🇨🇭", name: "Flag: Switzerland"),
        Emoji(symbol: "🇸🇾", name: "Flag: Syria"),
        Emoji(symbol: "🇹🇼", name: "Flag: Taiwan"),
        Emoji(symbol: "🇹🇯", name: "Flag: Tajikistan"),
        Emoji(symbol: "🇹🇿", name: "Flag: Tanzania"),
        Emoji(symbol: "🇹🇭", name: "Flag: Thailand"),
        Emoji(symbol: "🇹🇱", name: "Flag: Timor-Leste"),
        Emoji(symbol: "🇹🇬", name: "Flag: Togo"),
        Emoji(symbol: "🇹🇰", name: "Flag: Tokelau"),
        Emoji(symbol: "🇹🇴", name: "Flag: Tonga"),
        Emoji(symbol: "🇹🇹", name: "Flag: Trinidad & Tobago"),
        Emoji(symbol: "🇹🇦", name: "Flag: Tristan da Cunha"),
        Emoji(symbol: "🇹🇳", name: "Flag: Tunisia"),
        Emoji(symbol: "🇹🇷", name: "Flag: Turkey"),
        Emoji(symbol: "🇹🇲", name: "Flag: Turkmenistan"),
        Emoji(symbol: "🇹🇨", name: "Flag: Turks & Caicos Islands"),
        Emoji(symbol: "🇹🇻", name: "Flag: Tuvalu"),
        Emoji(symbol: "🇺🇬", name: "Flag: Uganda"),
        Emoji(symbol: "🇺🇦", name: "Flag: Ukraine"),
        Emoji(symbol: "🇦🇪", name: "Flag: United Arab Emirates"),
        Emoji(symbol: "🇬🇧", name: "Flag: United Kingdom"),
        Emoji(symbol: "🇺🇸", name: "Flag: United States"),
        Emoji(symbol: "🇺🇾", name: "Flag: Uruguay"),
        Emoji(symbol: "🇺🇿", name: "Flag: Uzbekistan"),
        Emoji(symbol: "🇻🇺", name: "Flag: Vanuatu"),
        Emoji(symbol: "🇻🇦", name: "Flag: Vatican City"),
        Emoji(symbol: "🇻🇪", name: "Flag: Venezuela"),
        Emoji(symbol: "🇻🇳", name: "Flag: Vietnam"),
        Emoji(symbol: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", name: "Flag: Wales"),
        Emoji(symbol: "🇼🇫", name: "Flag: Wallis & Futuna"),
        Emoji(symbol: "🇪🇭", name: "Flag: Western Sahara"),
        Emoji(symbol: "🇾🇪", name: "Flag: Yemen"),
        Emoji(symbol: "🇿🇲", name: "Flag: Zambia"),
        Emoji(symbol: "🇿🇼", name: "Flag: Zimbabwe"),
        Emoji(symbol: "🏳️", name: "White Flag"),
        Emoji(symbol: "🏴", name: "Black Flag"),
        Emoji(symbol: "🏁", name: "Chequered Flag"),
        Emoji(symbol: "🚩", name: "Triangular Flag"),
        Emoji(symbol: "🏳️‍🌈", name: "Rainbow Flag"),
        Emoji(symbol: "🏳️‍⚧️", name: "Transgender Flag"),
        Emoji(symbol: "🏴‍☠️", name: "Pirate Flag"),
        Emoji(symbol: "🇺🇳", name: "Flag: United Nations")
    ])
]
